### ISSUE TITLE
Dev Donation Fee

### ISSUE THREAD

**Issue by james3000119** [fireice-uk/xmr-stak-nvidia#101]
I would like to make a one time donation instead of the 1% dev fee, but I don't see where I can change it.  And please give me your xmr address so I can donate, thx!

**Comment by james3000119** [comment]
And also, what is the best setting for a gtx 1070?

**Comment by psychocrypt** [comment]
you can change this in https://github.com/fireice-uk/xmr-stak-nvidia/blob/master/donate-level.h please do not forget to donate both developer @fireice-uk and @psychocrypt 50/50 see https://github.com/fireice-uk/xmr-stak-nvidia
