### ISSUE TITLE
There is NO executable in the file list

### ISSUE THREAD

**Issue by Bobpick** [fireice-uk/xmr-stak-nvidia#108]
I looked through the archive - no .exe file.
I looked through the file list here on github - no exe file.

  |   | .gitignore
-- | -- | --
  |   | CMakeLists.txt
  |   | LICENSE
  |   | README.md
  |   | autoAdjust.hpp
  |   | cli-miner.cpp
  |   | config.txt
  |   | console.cpp
  |   | console.h
  |   | crypto/c_blake256.c
  |   | crypto/c_blake256.h
  |   | crypto/c_groestl.c
  |   | crypto/c_groestl.h
  |   | crypto/c_jh.c
  |   | crypto/c_jh.h
  |   | crypto/c_keccak.c
  |   | crypto/c_keccak.h
  |   | crypto/c_skein.c
  |   | crypto/c_skein.h
  |   | crypto/cryptonight.h
  |   | crypto/cryptonight_aesni.h
  |   | crypto/cryptonight_common.cpp
  |   | crypto/groestl_tables.h
  |   | crypto/hash.h
  |   | crypto/int-util.h
  |   | crypto/skein_port.h
  |   | crypto/soft_aes.c
  |   | donate-level.h
  |   | executor.cpp
  |   | executor.h
  |   | httpd.cpp
  |   | httpd.h
  |   | jconf.cpp
  |   | jconf.h
  |   | jext.h
  |   | jpsock.cpp
  |   | jpsock.h
  |   | libmicrohttpd/microhttpd.h
  |   | minethd.cpp
  |   | minethd.h
  |   | msgstruct.h
  |   | nvcc_code/cryptonight.h
  |   | nvcc_code/cuda_aes.hpp
  |   | nvcc_code/cuda_blake.hpp
  |   | nvcc_code/cuda_core.cu
  |   | nvcc_code/cuda_device.hpp
  |   | nvcc_code/cuda_extra.cu
  |   | nvcc_code/cuda_extra.h
  |   | nvcc_code/cuda_groestl.hpp
  |   | nvcc_code/cuda_jh.hpp

I reserve the right to be wrong, but danged if I can't find an .exe file.

**Comment by voltageat** [comment]
you need to go on "Releases" this what you see is the file liste from the Code! :)

**Comment by aegie** [comment]
that's the source to compile from. You need to get the binaries from here: https://github.com/fireice-uk/xmr-stak-nvidia/releases

**Comment by psychocrypt** [comment]
closed solution provided by @aegie
