### ISSUE TITLE
compiled version of linux

### ISSUE THREAD

**Issue by Chinafreak** [fireice-uk/xmr-stak-nvidia#128]
It would be nice if you could upload compiled linux version of xmr-stak-nvidia at release. I mean sure, I know how to build it. But I'm currently working on a project "gqu-miner" where you can mine multiple altcoins with collected miners and I don't want to install linux on pc. (later maybe). It would be also easier for other people if xmr-stak-nvidia/amd linux version were already compiled. :) 
I've already tried to compile from virtualbox, but looks like that you **really** need CUDA to compile which VirtualBox doesn't support, sadly.

Thanks

**Comment by rpinola** [comment]
I would also love if anybody could put binaries available. For the life of me I cannot complile this because cuda is such a mess.

**Comment by psychocrypt** [comment]
Maybe with the next release. Use the .run file which can be downloaded on
the nvidia side. Cuda installation is much easier than the opencl driver
from amd.

Am 28.09.2017 7:44 Nachm. schrieb "rpinola" <notifications@github.com>:

**Comment by rpinola** [comment]
I have used the .run files for the driver and cuda and installation went without problems. But the cuda SDK examples dont compile either. Maybe ill try ubuntu 17.04 next.

**Comment by psychocrypt** [comment]
Cuda can easily install on each linux without a gpu, a virtual should not be a problem.  
@Chinafreak  If you add xmr-stak to you miner please add the full source code how it is requested by the GPL.
