### ISSUE TITLE
Link errors during compile

### ISSUE THREAD

**Issue by codingoyster** [fireice-uk/xmr-stak-nvidia#129]
Hi, guys, can you please help? Tried to start from scratch multiple times, but receiving the same errors/warnings at compile time. Seems like I am missing a linked reference? I have only included the errors below, not the warnings. Thanks!

`cli-miner.obj : error LNK2001: unresolved external symbol ERR_load_BIO_strings [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
cli-miner.obj : error LNK2001: unresolved external symbol OpenSSL_add_all_digests [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
cli-miner.obj : error LNK2001: unresolved external symbol SSL_load_error_strings [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
cli-miner.obj : error LNK2001: unresolved external symbol SSL_library_init [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
cli-miner.obj : error LNK2001: unresolved external symbol ERR_load_crypto_strings [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_set_flags [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_new [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_free [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_read [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_write [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_puts [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_ctrl [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_push [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_free_all [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_s_mem [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_f_base64 [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol EVP_get_digestbyname [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol X509_digest [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol X509_free [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol BIO_new_ssl_connect [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol SSL_CTX_new [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol SSL_set_cipher_list [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol SSL_get_peer_certificate [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol SSL_CTX_ctrl [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol SSLv23_method [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
socket.obj : error LNK2001: unresolved external symbol ERR_print_errors [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]
C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\bin\Release\xmr-stak-nvidia.exe : fatal error LNK1120: 26 unresolved externals [C:\xmr-stak-dep\xmr-stak-nvidia-dev\build\xmr-stak-nvidia.vcxproj]`

**Comment by psychocrypt** [comment]
Do you used the dev branch? Please post all youtput from cmake, also before
the error.

Am 15.09.2017 23:26 schrieb "codingoyster" <notifications@github.com>:

**Comment by codingoyster** [comment]
Hi psychocrypt. I have attached the relevant files. error.txt has the command line compile error trace.

[CMakeError.txt](https://github.com/fireice-uk/xmr-stak-nvidia/files/1308539/CMakeError.txt)
[CMakeOutput.txt](https://github.com/fireice-uk/xmr-stak-nvidia/files/1308538/CMakeOutput.txt)
[error.txt](https://github.com/fireice-uk/xmr-stak-nvidia/files/1308537/error.txt)

**Comment by psychocrypt** [comment]
please use the dev branch and not the master. It is not possible to compile the master with cmake

**Comment by codingoyster** [comment]
Unless I missed something, I'm using the dev branch. I just downloaded and tried again with the same result.

**Comment by psychocrypt** [comment]
The windows path within the code is not including `pthread.h` but in your case it is included. I am not sure why.

**Comment by codingoyster** [comment]
I just tried on a new VM with a fresh install of Windows/VS 2017 and a fresh download of the dev branch. Same error.

Any tips to how I could remove the pthread.h reference. Or maybe steps to create a new solution within VS 2017 and then building from within VS 2017?

**Comment by codingoyster** [comment]
I guess another idea is try with cygwin installed on Windows?

**Comment by codingoyster** [comment]
I figured out the issue. My OpenSSL install was 32bit. Uninstalling and installing the 64bit version solved the errors.
