### ISSUE TITLE
OSX compilation error (non-constant-expression cannot be narrowed from type 'uint64_t')

### ISSUE THREAD

**Issue by MatthijsZw** [fireice-uk/xmr-stak-nvidia#130]
Compilation hangs at 80%:

`xmr-stak-nvidia-master/minethd.cpp:50:43: error: non-constant-expression cannot be narrowed from type 'uint64_t' (aka 'unsigned long long') to 'integer_t' (aka 'int') in initializer
      list [-Wc++11-narrowing]
        thread_affinity_policy_data_t policy = { cpu_id };`

And:

`xmr-stak-nvidia-master/minethd.cpp:256:3: error: no member named 'exit' in namespace 'std'; did you mean simply 'exit'?
                std::exit(0);
                ^~~~~~~~~
                exit`

I'm using clang 7.3.0 on OSX 10.12.6, with the latest CUDA + Patch and latest release from master-branch (915ed85)

**Comment by MatthijsZw** [comment]
I was too quick :)
I do not have this problem in the DEV-branch. You can close this issue.

**Comment by psychocrypt** [comment]
already solved in the dev branch
