### ISSUE TITLE
Solo mining?

### ISSUE THREAD

**Issue by cgarnier** [fireice-uk/xmr-stak-nvidia#131]
Hey,
How to solo mining ?

**Comment by psychocrypt** [comment]
Is only possible with a proxy for the monero demon (never tested). xmr-stak
supports only pool mining

Am 18.09.2017 7:59 Nachm. schrieb "Clément Garnier" <
notifications@github.com>:

**Comment by psychocrypt** [comment]
Maybe https://github.com/Snipa22/xmr-node-proxy can be used for solo mining but I am not sure.
