### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_60'

### ISSUE THREAD

**Issue by retronoodle** [fireice-uk/xmr-stak-nvidia#132]
I get the feeling that this is related to CUDA somehow, but I'm not sure - any ideas would be much appreciated!

**Comment by psychocrypt** [comment]
you are using CUDA 7 or 7.5. Please change the gpu architecture( s.
README.md) or update your cuda. CUDA 7.5 is not supporting pascal gpus.

Am 19.09.2017 5:32 Nachm. schrieb "Tim Monaghan" <notifications@github.com>:

**Comment by retronoodle** [comment]
Hi, thanks - so are you talking about doing something like this? 
`cmake . -DCUDA_ARCH=61`

Only I'm not sure what value would indicate 7.5 

Thanks again!

**Comment by mordka** [comment]
@retronoodle find your card on this list https://developer.nvidia.com/cuda-gpus and just copy these 2 digits

**Comment by jcklasseter** [comment]
@mordka I've a Tesla M60. Ive tried `cmake . -DCUDA_ARCH=52; make install`. I just get 'No CUDA device found on the binary's first run (null config.txt). Any ideas? It's CUDA 7.5, on a Ubuntu 16.04 system. 

The result of lspci is `00:1e.0 VGA compatible controller: NVIDIA Corporation GM204GL [Tesla M60] (rev a1)`

**Comment by mordka** [comment]
@jcklasseter it looks like it's another problem #2 That's all I know.

**Comment by jcklasseter** [comment]
@mordka Thanks for the link, but I don't even get a suggested output from the binary as they did there. Not your problem though. Maybe I'll open a new issue? I feel like there's alot of overlap with currently open issues though. Thanks regardless

**Comment by mordka** [comment]
@jcklasseter oh, there is another one here #39
Check if your CUDA driver works properly.

**Comment by psychocrypt** [comment]
Yes please check your cuda driver.

Am 22.09.2017 10:43 Nachm. schrieb "Paweł" <notifications@github.com>:

**Comment by rpinola** [comment]
I have this exact same issue and tried all that was suggested in this thread. It must be something related to cuda installation.

nvcc fatal   : Unsupported gpu architecture 'compute_61'

How would you check your cuda driver?

**Comment by psychocrypt** [comment]
Driver can be checked with 'nvidia-smi'.
If you are not owning a pascal gpu you can also set your architecture
explicit. -DCUDA_ARCH
For more information please see README.md.

Am 28.09.2017 1:26 Nachm. schrieb "rpinola" <notifications@github.com>:

**Comment by jcklasseter** [comment]
For me, it turns out I had everything installed correctly, I hadn't restarted the system recently enough and as such nvidia-smi didn't detect the card. After the restart nvidia-smi and the other problems were fixed.

**Comment by retronoodle** [comment]
Easiest way is to upgrade cuda to 8. Did you try that yet?

**Comment by rpinola** [comment]
@retronoodle 

I installed the latest cuda which was 9.0.

Using these installation files from Nvidia:

NVIDIA-Linux-x86_64-384.90.run
cuda_9.0.176_384.81_linux.run
gpucomputingsdk_4.0.17_linux.run

For Mint 18.2

**Comment by retronoodle** [comment]
Yeah, that's what ended up working for me - sorry I mistyped - it's 9 you
want.

Hopefully someone can help you out!

Thanks

**Comment by psychocrypt** [comment]
solved.

**Comment by monajalal** [comment]
for me I added 52 to my Dockerfile for M60 GPU and problem solved

```
    NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" \

```
