### ISSUE TITLE
Windows 10 MICROHTTPD cannot be found

### ISSUE THREAD

**Issue by srchulo** [fireice-uk/xmr-stak-nvidia#134]
Every time I run:

`cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 ..`

From [here](https://github.com/fireice-uk/xmr-stak-nvidia/blob/dev/WINCOMPILE.md), I get an error saying that microhttpd cannot be found. I do have it downloaded and I run this command:

`set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\libmicrohttpd-0.9.55-w32-bin\x86_64\VS2017\Release-static`

And it is in that location. I also set an environment variable named `MICROHTTPD_ROOT` as mentioned in the instructions.

**Comment by psychocrypt** [comment]
There is a bug in the code that the variable is not used for detection. You
can add the path to CMAKE_PREFIX_PATH else disable the dependency if you
need no http support.

Am 21.09.2017 8:05 Vorm. schrieb "Adam Hopkins" <notifications@github.com>:

**Comment by srchulo** [comment]
Thanks for the quick response!

I installed from the dev branch and then it worked. I'll close this unless you think this wasn't the solution.
