### ISSUE TITLE
double click what exe?

### ISSUE THREAD

**Issue by inigma117** [fireice-uk/xmr-stak-nvidia#135]
what exe do we double click for win users? I dont see any executables

**Comment by rumkuhgel** [comment]
Check your Anti-Virus, it most likely removed the exe file

**Comment by AKKenn** [comment]
Same issue. I cant even find an .exe file in the repository. Maybe I'm blind.

**Comment by psychocrypt** [comment]
You need to download the release zip file.
https://github.com/fireice-uk/xmr-stak-nvidia/releases

Am 24.09.2017 7:05 Vorm. schrieb "Ken Rose" <notifications@github.com>:

**Comment by AKKenn** [comment]
Yup that worked. Thanks :)
