### ISSUE TITLE
Unable to query number of CUDA devices!  Ubuntu 16.04 and GTX 970

### ISSUE THREAD

**Issue by Ethorsen** [fireice-uk/xmr-stak-nvidia#136]
Compiled with no problem.  Every dependency has been installed/updated.

Ubuntu 16.04
GTX 970

When I start the miner, it only outputs:
Unable to query number of CUDA devices!

If I try to force a gpu_config, it gives me the same error but only after trying to connect to pool. Plus an extra:
[2017-09-22 09:33:54] : Setup failed for GPU 0. Exitting.

Also tried to build specifying cuda arch with no luck
cmake . -DCUDA_ARCH=52

**Comment by staier** [comment]
i  have the same issue , i  wander  what  was the resolution

**Comment by psychocrypt** [comment]
Mostly it is an driver issue. What is the output of nvidia-smi

**Comment by staier** [comment]
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   59C    P0    N/A /  N/A |    377MiB /  4044MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2055      G   /usr/lib/xorg/Xorg                           172MiB |
|    0      5360      G   cinnamon                                      46MiB |
|    0      5568      G   /proc/self/exe                               157MiB |
`

**Comment by psychocrypt** [comment]
could you pease post the full log of xmr-stak.

**Comment by staier** [comment]
it  is weird,  but   now it works ,  the  only  thing i  did that  made it  was a reboot .
thank  you  anyway.
