### ISSUE TITLE
Failure and then auto close immediately

### ISSUE THREAD

**Issue by zhanghaoyue** [fireice-uk/xmr-stak-nvidia#140]
I run the xmr-stak-nvidia.exe, I think I saw some failure message but it happened too fast and it closed immediately.
I output the log but it does not show error:

[2017-09-30 23:08:01] : Connecting to pool pool.minexmr.com:5555 ...
[2017-09-30 23:08:01] : Connected. Logging in...
[2017-09-30 23:08:02] : Difficulty changed. Now: 15000.
[2017-09-30 23:08:02] : New block detected.
[2017-09-30 23:08:03] : New block detected.
[2017-09-30 23:11:41] : Connecting to pool pool.minexmr.com:5555 ...
[2017-09-30 23:11:41] : Connected. Logging in...
[2017-09-30 23:11:41] : Difficulty changed. Now: 15000.
[2017-09-30 23:11:41] : New block detected.

Is there a way to stop the program from auto closing?

**Comment by psychocrypt** [comment]
I think it is a wrong config. Please start the miner fom the terminal.
Also post your config and which gpu do you own.

Am 01.10.2017 8:15 Vorm. schrieb "Harry Zhang" <notifications@github.com>:

**Comment by zhanghaoyue** [comment]
"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 32, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],

I'm using a 1080 Ti.
I do open from terminal but it will pop a new console which is the same as I directly start the .exe

**Comment by psychocrypt** [comment]
Do you started from the terminal cmd?
Please lower the block count could be that you get an out of memory.

Am 01.10.2017 8:25 Nachm. schrieb "Harry Zhang" <notifications@github.com>:

**Comment by zhanghaoyue** [comment]
I started from cmd or powershell, it still opens a new console.
It works now as I lower the block counts. But still if you make it not close if encounter any error that would be great.

**Comment by psychocrypt** [comment]
Normally the miner wait before the shell is closed. But this is not the case if an error is triggered. I will keep it in mint and try to change it in the next release.

**Comment by psychocrypt** [comment]
Initial issues was solved by reducing the thread or block count.
