### ISSUE TITLE
Fails to build on powerpc with error cc: error: unrecognized command line option '-msse2'  

### ISSUE THREAD

**Issue by nithinswarrier** [fireice-uk/xmr-stak-nvidia#144]
I am trying to build on a powerpc but I cannot do it. The error which cmake makes is : 
```cc: error: unrecognized command line option '-msse2'                                                                                  
cc: error: unrecognized command line option '-maes'  ```
Please help me do it. I tried many other mining softwares but could not succeed.

**Comment by psychocrypt** [comment]
powerpc is not supported

Am 02.10.2017 5:15 Nachm. schrieb "Nithin S Warrier" <
notifications@github.com>:

**Comment by nithinswarrier** [comment]
Is there anyway I could make it work. Or please suggest any other miner which works with PowerPC.

**Comment by psychocrypt** [comment]
You can change the sse code with coresponding intrinsics.
I think therr is no miner dor powerpc(please ask google).
Do you have a openpower cpu or a real power pc?
How old is your power processor and what type is it.

Am 02.10.2017 6:40 Nachm. schrieb "Nithin S Warrier" <
notifications@github.com>:

**Comment by nithinswarrier** [comment]
I have a openpower cpu. cat /proc/cpuinfo doesn't give anything in much detail. It just shows that there is 160 cores. Nothing else.

**Comment by psychocrypt** [comment]
power 8, 8+ or power 9? But anyway it is not supported :-(

Am 02.10.2017 6:45 Nachm. schrieb "Nithin S Warrier" <
notifications@github.com>:

**Comment by nithinswarrier** [comment]
Power8
