### ISSUE TITLE
How to connect to web server

### ISSUE THREAD

**Issue by AKKenn** [fireice-uk/xmr-stak-nvidia#153]
How exactly do I set up the built-in web server? I tried changing the httpd_port setting in the config file but I cant seem to figure it out. I'm just trying to connect on the home network. No port forwarding needed.

**Comment by tlorens** [comment]
Set the port and point your browser to the `http://<ip>:<port>` of the machine the miner is running on.

**Comment by AKKenn** [comment]
Perfect. Thank you!
