### ISSUE TITLE
No cuda device - w10 x64 - quadro fx 1800

### ISSUE THREAD

**Issue by damsterdam06** [fireice-uk/xmr-stak-nvidia#164]
Hello all !
Thanks in advance for all your advices and help.
I would like to use my old Quadro fx1800 on w10 x64 to mine with xmr, but can't find the cuda driver for it so xmr says "no cuda device" before quitting
Any idea ? 
thanks !

**Comment by psychocrypt** [comment]
This old gpu is not supported bei cuda 8. Also the miner will not support
this card. You need at least sm_20 (fermi). Your card is one of the first
cards with cuda support.

**Comment by damsterdam06** [comment]
Thanks for your reply, after hours of search i confirm... yes one of the first, it was ready to go at the garbage so I give it a try.
Anyways on xmrpool chan I found someone in Bulgaria who would like to use it for video editing so... it will still make someone happy for free ;)
