### ISSUE TITLE
Ubuntu GTX 660 GPU 0: Invalid Argument

### ISSUE THREAD

**Issue by Sesh360** [fireice-uk/xmr-stak-nvidia#168]
Getting this error when running the miner.

Recommended Config looks valid with 32 threads and 15 blocks, but fails with above error.

If I set it to 1 thread and 1 block it runs without the listed error.

CMake . DCUDA_ARCH=30

Can't seem to figure out what the issue is.

Thanks in advanced.

**Comment by psychocrypt** [comment]
Please poat the suggested config. How much memory has your gpu.
Try to use the autosuggested config und reduce the number of threads step
by step by two.

**Comment by Sesh360** [comment]
GPU Memory: 3 GB

This is the suggested config:

{"index" : 0, "threads" : 32, "blocks" : 15, "bfactor" : 0, "bsleep" : 0, "affine_to_cpu" : false,},

I stepped the threads down and it still fails with the same message.

**Comment by sheepchen** [comment]
I am not entirely sure, but my GTX 660 TI was not supported (even I have compiled directly for it).

But try the following: remove the comma behind false and behind } .

The same binary runs like charm with newer cards (1060)

**Comment by Sesh360** [comment]
@sheepchen 

Removed commas - same error

Changed bfactor and bsleep - same thing.

I should mention that I am running a server version of Ubuntu 16.04.3 LTS. So my assumption is that the bsleep and bfactor should be 0?

**Comment by psychocrypt** [comment]
Yes bfactor on linux can be zero. You could try to compile for all
architectures. Cleanup all temporary files qnd run cmake without setting
CUDA_ARCH. The compile will take a few minutes.

**Comment by Sesh360** [comment]
@psychocrypt @sheepchen 

Thanks for your help. Cleaned everything out and git cloned fresh.

Ran CMake . -DCUDA-ARCH=30 and Make Install with the config listed prior.

For some reason this time it worked correctly. 263.9 H/s.

Thanks again and enjoy your weekend!
