### ISSUE TITLE
Windows 10 with CUDA 9 compile

### ISSUE THREAD

**Issue by Antreasgr** [fireice-uk/xmr-stak-nvidia#172]
I tried to compile on Windows 10 with Visual Studio 2017 and Cuda 9.0, and i am getting the following error:

` Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cu
  da_backend_generated_cuda_core.cu.obj
  CMake Error at xmrstak_cuda_backend_generated_cuda_core.cu.obj.Release.cmake:219 (message):
    Error generating
    C:/Users/Antreas/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cuda
  _backend_generated_cuda_core.cu.obj`

The full logs running the CMake generation and compiling is in the attached file.
[log.txt](https://github.com/fireice-uk/xmr-stak-nvidia/files/1444271/log.txt)

**Comment by davidgiga1993** [comment]
How did you fix this? I'm also getting this error
