### ISSUE TITLE
Setup failed for GPU 1

### ISSUE THREAD

**Issue by andreionescu03** [fireice-uk/xmr-stak-nvidia#173]
[2017-11-06 20:57:06] : Connecting to pool electroneum.hashparty.io:7777 ...
[2017-11-06 20:57:07] : Connected. Logging in...
[2017-11-06 20:57:07] : Difficulty changed. Now: 10000.
[2017-11-06 20:57:07] : New block detected.
[2017-11-06 20:57:08] : Setup failed for GPU 1. Exitting.

nVidia 950M 4GB
Why? 
"gpu_threads_conf" : [
{ "index" : 0,
    "threads" : 20, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 1,
    "threads" : 21, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 2,
    "threads" : 22, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 3,
    "threads" : 23, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 4,
    "threads" : 24, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },

],

**Comment by psychocrypt** [comment]
Please use for all gpus 20 threads. Do not increase the threads per gpu.

**Comment by andreionescu03** [comment]
@psychocrypt done that. Now getting the same error for GPU 3.

**Comment by psychocrypt** [comment]
please post the config and the type of the gpus

**Comment by andreionescu03** [comment]
@psychocrypt 
/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 * 
 * A filled out configuration should look like this:
 * "gpu_threads_conf" : 
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
 * ],
 */
"gpu_threads_conf" : [
{ "index" : 0,
    "threads" : 20, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 1,
    "threads" : 20, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 2,
    "threads" : 20, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 3,
    "threads" : 20, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
{ "index" : 4,
    "threads" : 20, "blocks" : 30,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },

],
/*
 * TLS Settings
 * If you need real security, make sure tls_secure_algo is enabled (otherwise MITM attack can downgrade encryption
 * to trivially breakable stuff like DES and MD5), and verify the server's fingerprint through a trusted channel. 
 *
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_secure_algo - Use only secure algorithms. This will make us quit with an error if we can't negotiate a secure algo.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 */
"use_tls" : false,
"tls_secure_algo" : true,
"tls_fingerprint" : "",

/*
 * pool_address	  - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address - Your wallet, or pool login.
 * pool_password  - Can be empty in most cases or "x".
 */
"pool_address" : "electroneum.hashparty.io:7777",
"wallet_address" : "etnk72ezNmsUQuVFLMs5kWDGsFFPYFhqRcevxPkLzg4NcweWVWvNLLs7FmhtAKfSxBK57AntEHPPU6SbpRXoaZKK2cdmp38QQD",
"pool_password" : "",

/*
 * Network timeouts.
 * Because of the way this client is written it doesn't need to constantly talk (keep-alive) to the server to make 
 * sure it is there. We detect a buggy / overloaded server by the call timeout. The default values will be ok for 
 * nearly all cases. If they aren't the pool has most likely overload issues. Low call timeout values are preferable -
 * long timeouts mean that we waste hashes on potentially stale jobs. Connection report will tell you how long the
 * server usually takes to process our calls.
 *
 * call_timeout - How long should we wait for a response from the server before we assume it is dead and drop the connection.
 * retry_time	- How long should we wait before another connection attempt.
 *                Both values are in seconds.
 * giveup_limit - Limit how many times we try to reconnect to the pool. Zero means no limit. Note that stak miners
 *                don't mine while the connection is lost, so your computer's power usage goes down to idle.
 */
"call_timeout" : 10,
"retry_time" : 10,
"giveup_limit" : 0,

/*
 * Output control.
 * Since most people are used to miners printing all the time, that's what we do by default too. This is suboptimal
 * really, since you cannot see errors under pages and pages of text and performance stats. Given that we have internal
 * performance monitors, there is very little reason to spew out pages of text instead of concise reports.
 * Press 'h' (hashrate), 'r' (results) or 'c' (connection) to print reports.
 *
 * verbose_level - 0 - Don't print anything. 
 *                 1 - Print intro, connection event, disconnect event
 *                 2 - All of level 1, and new job (block) event if the difficulty is different from the last job
 *                 3 - All of level 1, and new job (block) event in all cases, result submission event.
 *                 4 - All of level 3, and automatic hashrate report printing 
 */
"verbose_level" : 3,

/*
 * Automatic hashrate report
 *
 * h_print_time - How often, in seconds, should we print a hashrate report if verbose_level is set to 4.
 *                This option has no effect if verbose_level is not 4.
 */
"h_print_time" : 60,

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "1.txt",

/*
 * Built-in web server
 * I like checking my hashrate on my phone. Don't you?
 * Keep in mind that you will need to set up port forwarding on your router if you want to access it from
 * outside of your home network. Ports lower than 1024 on Linux systems will require root.
 *
 * httpd_port - Port we should listen on. Default, 0, will switch off the server.
 */
"httpd_port" : 0,

/*
 * prefer_ipv4 - IPv6 preference. If the host is available on both IPv4 and IPv6 net, which one should be choose?
 *               This setting will only be needed in 2020's. No need to worry about it now.
 */
"prefer_ipv4" : true,

nVidia GTX 950M

**Comment by psychocrypt** [comment]
windows or linux?
Do you started with the auto suggestion?
If you use linux please post the output of nvidia-smi

**Comment by andreionescu03** [comment]
@psychocrypt Windows 10 
I started the program 1 time, then configured it as you see above

**Comment by psychocrypt** [comment]
On windows bfactor should be 6 and bsleep 25

**Comment by andreionescu03** [comment]
@psychocrypt modified that. Still the same error but now GPU 1 again.

**Comment by psychocrypt** [comment]
Please post the full output of the miner including the error

**Comment by andreionescu03** [comment]
@psychocrypt Ok, so... I restarted everything. I deleted everything, downloaded it again and started to config it again. As soon as I copy  { "index" : 0,
    "threads" : 32, "blocks" : 15,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
the second time, I get that error : 
[2017-11-06 21:44:04] : Connecting to pool electroneum.hashparty.io:7777 ...
[2017-11-06 21:44:04] : Connected. Logging in...
[2017-11-06 21:44:04] : Difficulty changed. Now: 10000.
[2017-11-06 21:44:04] : New block detected.
[2017-11-06 21:44:06] : Setup failed for GPU 1. Exitting.

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 * 
 * A filled out configuration should look like this:
 * "gpu_threads_conf" : 
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
 * ],
 */
"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 32, "blocks" : 15,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
{ "index" : 1,
    "threads" : 32, "blocks" : 15,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },

],

/*
 * TLS Settings
 * If you need real security, make sure tls_secure_algo is enabled (otherwise MITM attack can downgrade encryption
 * to trivially breakable stuff like DES and MD5), and verify the server's fingerprint through a trusted channel. 
 *
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_secure_algo - Use only secure algorithms. This will make us quit with an error if we can't negotiate a secure algo.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 */
"use_tls" : false,
"tls_secure_algo" : true,
"tls_fingerprint" : "",

/*
 * pool_address	  - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address - Your wallet, or pool login.
 * pool_password  - Can be empty in most cases or "x".
 */
"pool_address" : "electroneum.hashparty.io:7777",
"wallet_address" : "etnk72ezNmsUQuVFLMs5kWDGsFFPYFhqRcevxPkLzg4NcweWVWvNLLs7FmhtAKfSxBK57AntEHPPU6SbpRXoaZKK2cdmp38QQD",
"pool_password" : "",

/*
 * Network timeouts.
 * Because of the way this client is written it doesn't need to constantly talk (keep-alive) to the server to make 
 * sure it is there. We detect a buggy / overloaded server by the call timeout. The default values will be ok for 
 * nearly all cases. If they aren't the pool has most likely overload issues. Low call timeout values are preferable -
 * long timeouts mean that we waste hashes on potentially stale jobs. Connection report will tell you how long the
 * server usually takes to process our calls.
 *
 * call_timeout - How long should we wait for a response from the server before we assume it is dead and drop the connection.
 * retry_time	- How long should we wait before another connection attempt.
 *                Both values are in seconds.
 * giveup_limit - Limit how many times we try to reconnect to the pool. Zero means no limit. Note that stak miners
 *                don't mine while the connection is lost, so your computer's power usage goes down to idle.
 */
"call_timeout" : 10,
"retry_time" : 10,
"giveup_limit" : 0,

/*
 * Output control.
 * Since most people are used to miners printing all the time, that's what we do by default too. This is suboptimal
 * really, since you cannot see errors under pages and pages of text and performance stats. Given that we have internal
 * performance monitors, there is very little reason to spew out pages of text instead of concise reports.
 * Press 'h' (hashrate), 'r' (results) or 'c' (connection) to print reports.
 *
 * verbose_level - 0 - Don't print anything. 
 *                 1 - Print intro, connection event, disconnect event
 *                 2 - All of level 1, and new job (block) event if the difficulty is different from the last job
 *                 3 - All of level 1, and new job (block) event in all cases, result submission event.
 *                 4 - All of level 3, and automatic hashrate report printing 
 */
"verbose_level" : 3,

/*
 * Automatic hashrate report
 *
 * h_print_time - How often, in seconds, should we print a hashrate report if verbose_level is set to 4.
 *                This option has no effect if verbose_level is not 4.
 */
"h_print_time" : 60,

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "1.txt",

/*
 * Built-in web server
 * I like checking my hashrate on my phone. Don't you?
 * Keep in mind that you will need to set up port forwarding on your router if you want to access it from
 * outside of your home network. Ports lower than 1024 on Linux systems will require root.
 *
 * httpd_port - Port we should listen on. Default, 0, will switch off the server.
 */
"httpd_port" : 0,

/*
 * prefer_ipv4 - IPv6 preference. If the host is available on both IPv4 and IPv6 net, which one should be choose?
 *               This setting will only be needed in 2020's. No need to worry about it now.
 */
"prefer_ipv4" : true,

**Comment by psychocrypt** [comment]
why do you copied the first threadconfig again? The auto suggestion should
find all gpus and create a config for you.

**Comment by andreionescu03** [comment]
@psychocrypt https://bitcointalk.org/index.php?topic=2345911.0 this is what it says here

**Comment by psychocrypt** [comment]
please contact me via reddit (user: psychocrypt)

**Comment by psychocrypt** [comment]
We released a new version of the miner: https://github.com/fireice-uk/xmr-stak
Please check if the issue still exists with the new version. 
If the problem is not fixed so far please open a new issue in [the issue section of the new reposetory](https://github.com/fireice-uk/xmr-stak/issues)
