### ISSUE TITLE
microhttpd NOT found

### ISSUE THREAD

**Issue by Omgthehorror** [fireice-uk/xmr-stak-nvidia#178]
I'm getting this error, when trying to compile on win 10. What is the cause? libmicrohttpd-0.9.55-w32-bin is unzipped in C:\xmr-stak-dep and the structure is the same as in the guide.

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:153 (message):
  microhttpd NOT found: use `-DMICROHTTPD_REQUIRED=OFF` to build without http
  deamon support

-- Configuring incomplete, errors occurred!

**Comment by pfreindorf** [comment]
Hi,

I have exactly the same error. Did you solve it ?

Thanks.

Pierre

**Comment by psychocrypt** [comment]
please use the new miner release https://github.com/fireice-uk/xmr-stak

Please check the new install instructions and download the new dependencies
to avoid incompatibility.
Open an issue in the new reposetory if you have problems.
Add all comamnds and the full output you used.
