### ISSUE TITLE
Linux GUI freeze when running miner

### ISSUE THREAD

**Issue by pascalwacker** [fireice-uk/xmr-stak-nvidia#179]
Hi

I've compiled the xmr-stak-nvidia miner on a Ubuntu 17.04 laptop, using clang-3.8
```
export CC=/usr/bin/clang-3.8
export CXX=/usr/bin/clang++-3.9
```
as both 3.9 and 4.0 had the unsupported issue. The Videocard is a [Nvidia GeForce 740M](https://www.geforce.com/hardware/notebook-gpus/geforce-gt-740m)

I've set `verbose_level` to 4 and configured an output file.

When running from pure CLI mode (`Ctrl+Alt+F1`), it works but when I run it from the GUI mode (`Ctrl+Alt+F7`), _note: the GUI mode is the default mode_, the screen freezes and I can't do anything except for shuting down the laptop by long pressing the power button.

Is there a config option to not use 100% of the GPU power?

btw. thanks for your work! it's much appreciated.

**Comment by psychocrypt** [comment]
We released a new version of the miner: https://github.com/fireice-uk/xmr-stak
Please check if the issue still exists with the new version. 
If the problem is not fixed so far please open a new issue in [the issue section of the new reposetory](https://github.com/fireice-uk/xmr-stak/issues)
