### ISSUE TITLE
 JSON config parse error(offset 3299): Invalid escape character in string.

### ISSUE THREAD

**Issue by T0MTOM1** [fireice-uk/xmr-stak-nvidia#181]
JSON config parse error(offset 3299): Invalid escape character in string.

**Comment by psychocrypt** [comment]
We released a new version of the miner: https://github.com/fireice-uk/xmr-stak
Please check if the issue still exists with the new version. 
If the problem is not fixed so far please open a new issue in [the issue section of the new reposetory](https://github.com/fireice-uk/xmr-stak/issues)
