### ISSUE TITLE
GPU 0: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Talej** [fireice-uk/xmr-stak-nvidia#184]
I have the same issue as #159 and have adjusted DCUDA_ARCH but no joy...

I'm getting this error on CentOS 7 with a GeForce GTX 570M and CUDA 9. I've tried DCUDA_ARCH (have played around with difference values just to be sure) but still same problem.

Any other hints?

**Comment by psychocrypt** [comment]
please use our latest release https://github.com/fireice-uk/xmr-stak

**Comment by Talej** [comment]
Thanks for the reply. Can't get xmr-stak to even compile properly with CUDA support :(

**Comment by psychocrypt** [comment]
please post the commands used to compile the miner and the output which is
produced which leads to the point that you can:t compile with cuda support.

**Comment by Talej** [comment]
Sorry, that would have been helpful if I posted it...

```
    git clone https://github.com/fireice-uk/xmr-stak.git
    mkdir xmr-stak/build
    cd xmr-stak/build
    cmake3 .. -DCPU_ENABLE=ON -DCUDA_ENABLE=ON -DCUDA_ARCH=21 -DOpenCL_ENABLE=OFF
    make install
```

All works okay up until make install when I get (also tried with arch 20):

> [ 86%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
> nvcc fatal   : Unsupported gpu architecture 'compute_21'
> CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:207 (message):
>   Error generating
>   /root/miner/round2/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o
> 
> 
> make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
> make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
> make: *** [all] Error 2

Note that I was able to get it to make install if I use CUDA_ARCH=52 but then if I run xmr-stak I get:

> WARNING: NVIDIA GPU 0: miner not compiled for the gpu architecture 20.
> [2017-11-21 19:18:02] : WARNING: NVIDIA setup failed for GPU 0.

**Comment by psychocrypt** [comment]
Please change the architecture 21 to 20. 21 is only a virtual architecture
therefore 20 must be used.

**Comment by Talej** [comment]
I get the same problem when using 20:

[ 83%] Built target xmr-stak
[ 86%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_20'
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:207 (message):
  Error generating
  /root/miner/round2/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o


> make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
> make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
> make: *** [all] Error 2

**Comment by psychocrypt** [comment]
Do you use cuda9? If so cuda9 is not longer supporting fermi (20) gpus. You
must download cuda8 to compile for fermi gpus.

**Comment by Talej** [comment]
Yep, using cuda9. I'll give cuda8 a try

**Comment by Talej** [comment]
I've got it mostly working now, thanks so much. I do have an AMD card to get working with it as well but that is seeming like too much trouble (problems with getting OpenCL working in CentOS 7.3) so I might just swap them over to all NVIDIA cards.

Thanks again.
