### ISSUE TITLE
hwloc: memory pinned but memory access error 

### ISSUE THREAD

**Issue by Pentoman** [fireice-uk/xmr-stak-nvidia#185]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.13-1kali1 (2017-11-17)

Version: xmr-stak 2.0.0 79154f7
self compile

running xmr.....

-------------------------------------------------------------------
xmr-stak 2.0.0 79154f7

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.

Configurable dev donation level is set to 0.0% (if this prog would work i would think about donation) 

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-11-22 20:53:31] : Start mining: MONERO
[2017-11-22 20:53:31] : Starting NVIDIA GPU thread 0, no affinity.
[2017-11-22 20:53:31] : Starting single thread, no affinity.
[2017-11-22 20:53:31] : Starting single thread, no affinity.
[2017-11-22 20:53:31] : Starting single thread, no affinity.
Speicherzugriffsfehler 

this means memory access error

also setting all to affinity is not helping tried all possible settings...
running as root is not helping 
setting to deamon is not helping 
setting sudo sysctl -w vm.nr_hugepages=128 is not helping
editing and adding * soft memlock 262144 * hard memlock 262144 /etc/security/limits.conf is not helping
please give some help 
tried all possible settings , rebooted etc.
setting use_slow_mem to always or no_mlck is not helping.

**Comment by gvjtownsend** [comment]
Was there no solution for this? Its closed ... I'm having the same trouble, but it only started after I added an AMD card to a working system with an NVIDIA card ... the NVIDA was fine before this, but now it gives this problem.

**Comment by psychocrypt** [comment]
please check if the issue is solved with the new release
https://github.com/fireice-uk/xmr-stak/releases
