### ISSUE TITLE
microhttpd NOT found

### ISSUE THREAD

**Issue by pfreindorf** [fireice-uk/xmr-stak-nvidia#186]
Hi,

Trying to compile on Windows 7 64 with cuda 9 for nvidia hw 1050 Ti. 

C:\mining\xmr-stak-nvidia-final\build>cmake -G "Visual Studio 15 2017 Win64" -T
v141,host=x64 ..
CMake Warning (dev) at CMakeLists.txt:27 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:47 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:153 (message):
  microhttpd NOT found: use `-DMICROHTTPD_REQUIRED=OFF` to build without http
  deamon support

-- Configuring incomplete, errors occurred!
See also "C:/mining/xmr-stak-nvidia-final/build/CMakeFiles/CMakeOutput.log".
See also "C:/mining/xmr-stak-nvidia-final/build/CMakeFiles/CMakeError.log".

Looked in the logs and it searches for file pthread.h which is not present anywhere ...

Some help appreciated ...

Thanks.

Pierre

**Comment by psychocrypt** [comment]
Please use the new release https://github.com/fireice-uk/xmr-stak

**Comment by pfreindorf** [comment]
It works better, thanks for your quick reply.
