### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_70' (mac nvidia)

### ISSUE THREAD

**Issue by twidlr** [fireice-uk/xmr-stak-nvidia#198]
Hello,

I'm trying to compile on Mac Os High Sierra 10.13.2 (17C88)

Everything checks out except for Building NVCC
```
nvcc fatal   : Unsupported gpu architecture 'compute_70'
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:219 (message):
  Error generating
/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o
```

My graphics card is a GTX 980 ti

Does anyone know how to resolve this?

Thanks

**Comment by davidwowa** [comment]
what was a solution for yours problem?

**Comment by twidlr** [comment]
@davidwowa check https://github.com/fireice-uk/xmr-stak/issues/492 for compiling the unified miner (which is the latest version)
Still unresolved for me. If I understand correctly there is a bug that prevents it from compiling correctly with the latest version of clang and Cuda on mac os. Compiling with older versions should work, but I haven't tried it.
Can you report the steps in case you can make it work?

Cheers

**Comment by davidwowa** [comment]
@twidlr in CUDA description I found this:

Note that the CUDA 9.1 driver supports macOS 10.13. This means that existing CUDA applications can be run on Mac systems with CUDA 9.1 installed, however new CUDA applications cannot be compiled with CUDA 9.1 on macOS 10.13.

Read more at: http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html#ixzz53hQs8FRU 
Follow us: @GPUComputing on Twitter | NVIDIA on Facebook

And I have a macOS 10.13 :-(.

**Comment by twidlr** [comment]
@davidwowa me too :-( we better switch to windows then :-(

**Comment by davidwowa** [comment]
Driver support for Mac OS 10.13.1 is added in this release. Note that existing CUDA applications can be run on Mac OS 10.13.1 with CUDA 9.1 installed. However, CUDA 9.1 does not support building applications with Xcode 9.1. Support for building applications with Xcode 9.1 is planned for a future release of CUDA.

Read more at: http://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#ixzz55EgUGvDJ 
Follow us: @GPUComputing on Twitter | NVIDIA on Facebook
