### ISSUE TITLE
Older nVidia Quadros not working

### ISSUE THREAD

**Issue by ghost** [fireice-uk/xmr-stak-nvidia#221]
I got an FX 1700, FX 380 and some more old quadros.

They dont work? why?

**Comment by psychocrypt** [comment]
Because nvidia closed the driver and compiler support years ago for this
old gpus.

**Comment by zod11** [comment]
Is Quadro K620 also considered old? Can't get it to work, it starts mining but gives 0.0H/s

**Comment by ghost** [comment]
It should work. Just wait for some time while spamming "h".
My Quadro K4000 also gives an output periodically

**Comment by zod11** [comment]
> It should work. Just wait for some time while spamming "h". My Quadro K4000 also gives an output periodically

Yeah, I needed to wait a bit, it works great

**Comment by y1111** [comment]
does gt 240 work ? cuda 1.2

and quadro fx1800 ? cuda 1.1 .

using cuda 6.5 toolkit.

whats the minimum cuda suported ?

**Comment by ghost** [comment]
Quadro FX1800 does not work, i can tell you because mine didnt either.

GT240, dont know
