### ISSUE TITLE
Still can't mine on my nvidia GT 640

### ISSUE THREAD

**Issue by schniffer** [fireice-uk/xmr-stak-nvidia#223]
I need help running xmr-stak-nvidia as this would be my last choice to mine on a not so old GPU of mine, my OS is windows 7.

When I run the exe file on my pc with gtx 750 it shows the recommended config to use 
but when I run it on my pc with the gtx 640 it the program seems to automatically exit.

I just want to know if I might be missing something to enable the miner to work on these type of gpu as I can't seem to find a workaround anywhere and whenever I update my drivers to the latest version of nvidia, gpu always had error code 43 on the device manager.

Here's my config file
[config.txt](https://github.com/fireice-uk/xmr-stak-nvidia/files/1793538/config.txt)
and here's the outputfile.
[miningoutput.txt](https://github.com/fireice-uk/xmr-stak-nvidia/files/1793526/miningoutput.txt)

**Comment by psychocrypt** [comment]
which driver do you use. Please fill the temlate out else we have not
enough information

**Comment by schniffer** [comment]
The nvidia driver version sir 337.5

I can't seem to find the template you're referring to please point me too it thanks.

**Comment by VITALFORCE47** [comment]
Dear all

 

I have been trying to mine with awesome miner for the last couple of weeks but I could not get my gpu to mine. I have got very old NVIDIA GTX 560 TI which is CUDA supported. My CPU mine with no trouble but with my GPU I had no luck. Could you please point the problem if you could your kind help will be greatly appreciated. Here is my diagnostic report.

 

Kind Regards

 

Fayik Ozgun

 

 

Starting Diagnostics. Awesome Miner version: 4.5.3

Starting Mining Software

Setting up Miner Engine. Instance: 2

Engine Type: CcMiner, Auto Download: True, EnginePath: , Subtype: Disabled, CustomExecutable:

Added rule for: C:\Users\Robin\AppData\Local\AwesomeMiner\ccminer-2.2.4_2\ccminer-x64-2.2.4-cuda9\ccminer-x64.exe

C:\Users\Robin\AppData\Local\AwesomeMiner\ccminer-2.2.4_2\ccminer-x64-2.2.4-cuda9\ccminer-x64.exe  -a cryptonight -o stratum+tcp://eu2.electromine.fr:3333 -u etnk8iRfSJH6JEpisqX4uNZqFJq8RZpj7dDuNmjQCVcdVzLKpzygYwm3s7aGFqbegGagEoLpfSAQPGsKfsh971AU2fWVwTKnBi -p x -b 0.0.0.0:4029   (WindowMode: ConsoleFormat, EngineType: CcMiner, IsProfitMiner: False)

Configuration:

 

Mining Engine Process started, PID: 10692

 

====================================================================================================

> *** ccminer 2.2.4 for nVidia GPUs by tpruvot@github ***

>     Built with VC++ 2013 and nVidia CUDA SDK 9.0 64-bits

>

>   Originally based on Christian Buchner and Christian H. project

>   Include some kernels from alexis78, djm34, djEzo, tsiv and krnlx.

>

> BTC donation address: 1AJdfCpLWPNoAMDfHF1wD5y8VgKSSTHxPo (tpruvot)

>

> [2018-03-14 23:13:23] Using JSON-RPC 2.0[0m

> [2018-03-14 23:13:23][36m Starting on stratum+tcp://eu2.electromine.fr:3333[0m

> [2018-03-14 23:13:23] NVML GPU monitoring enabled.[0m

> [2018-03-14 23:13:23] NVAPI GPU monitoring enabled.[0m

> [2018-03-14 23:13:23] 1 miner thread started, using 'cryptonight' algorithm.[0m

> [2018-03-14 23:13:23][33m Stratum difficulty set to 5000 (5)[0m

> [2018-03-14 23:13:23] GPU #0: GeForce GTX 560 Ti, 853 MB available, 8 SMX[0m

> [2018-03-14 23:13:23] GPU #0: 256 threads (8) with 32 blocks[0m

> [2018-03-14 23:13:23][31m GPU #0: no kernel image is available for execution on the device cryptonight_extra_cpu_prepare line 217[0m

 

====================================================================================================

Unexpected exit of mining software. Possible cause: Incorrect configuration

Diagnostics completed

**Comment by psychocrypt** [comment]
lease do not post errors from other miners to this reposetory. This is the
repo of xmr-stak

**Comment by psychocrypt** [comment]
https://github.com/fireice-uk/xmr-stak/
