### ISSUE TITLE
XMR-Stak error when configured only for GPU

### ISSUE THREAD

**Issue by IronDruidHound** [fireice-uk/xmr-stak-nvidia#224]
I have a machine with Nvidia GeForce 770M GPU.  When I changed the CPU config to not use CPU, I get the following error:

Start Mining: MONERO
Starting NVIDIA GPU thread 0, no affinity
WARNING:  No AMD OpenCL platform found.  Possible driver issues or wrong vendor driver.
WARNING:  backend AMD disabled
JSON config parse error (offset 1642): Missing a name for object member

Press any key to exit

I have updated the driver on the graphics card to latest driver but I am still getting the same issue.

Has anyone else seen this?

**Comment by IronDruidHound** [comment]
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 770M architecture: 30
  //      memory: 2559/3072 MiB
  //      smx: 5
  { "index" : 0,
    "threads" : 50, "blocks" : 15,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by psychocrypt** [comment]
please remove cpu.txt and let the miner generate a new config. If you like
to disable cpu mining start the miner with the option --noCPU

**Comment by psychocrypt** [comment]
You posted this issue in the wrong reposetory, please switch to 
https://github.com/fireice-uk/xmr-stak/
