### ISSUE TITLE
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll

### ISSUE THREAD

**Issue by rickbb** [fireice-uk/xmr-stak-nvidia#238]
I've tried using the search, but either I'm not doing it right or maybe it's an actual new issue.

New 4gb GTX 1050 card, 640 cuda cores 391.x drivers, win 10 ENT LTSB 64 bit.

Using the latest binary from here, keep getting the cannot load backend library error on starting xmr.

Can someone point in the direction to solve this?

Thanks,

**Comment by psychocrypt** [comment]
your av software remived some files. Please add a exeption for the folder
to your av software and redownload all.

**Comment by rickbb** [comment]
Thanks, issue solved. I had added the folder as an exception, but Webroot wasn't behaving apparently. uninstalled it and tried again. working now.
