### ISSUE TITLE
v1.1.0-1.4.0 not working on GT 740M

### ISSUE THREAD

**Issue by miziel** [fireice-uk/xmr-stak-nvidia#30]
Laptop with integrated Intel HD 4600 and secondary GeForce GT 740M.

Version v1.0.1-1.3.1 works fine with:
{ "index" : 0, "threads" : 48, "blocks" : 8, "bfactor" : 8, "bsleep" :  0, "affine_to_cpu" : false}

Version v1.1.0-1.4.0 with same specs gives error:
GPU 0: an illegal memory access was encountered
C:/Users/MAIN/Documents/Visual Studio 2015/Projects/xmr-stak-nvidia/xmr-stak-nvidia/nvcc_code/cuda_extra.cu line 246

**Comment by fireice-uk** [comment]
Nice to see you again! @psychocrypt identified an issue with my build settings. Originally I was going to join up this update with a new CPU release not to spam reddit too much, however there are more issues with the release than anticipated. I will do the update tonight, so stay tuned.

**Comment by psychocrypt** [comment]
This issue is equal to #28.

**Comment by miziel** [comment]
@fireice-uk Ah, so I'll wait patiently - although I'm going for a leave so maybe I'll play with own builds again 
@psychocrypt I skimmed through the issues and honestly didn't notice... My bad, I am tired :) 
So, I close this one

**Comment by fireice-uk** [comment]
Just an update, I uploaded an extended build yesterday. This should resolve your issues. If you have any more problems, please open another issue.
