### ISSUE TITLE
i dont find the .exe

### ISSUE THREAD

**Issue by Dethmocritus** [fireice-uk/xmr-stak-nvidia#32]
i dont understand or dont find the .exe for start mining. Thx for any help

**Comment by psychocrypt** [comment]
- klick [here](https://github.com/fireice-uk/xmr-stak-nvidia/releases/tag/v1.1.1-1.4.0) and download the zip files. 
- exreakt the zip file (exe is included)

**Comment by psychocrypt** [comment]
closed should be issue solved
