### ISSUE TITLE
Can't find referenced .exe file

### ISSUE THREAD

**Issue by ajferrario** [fireice-uk/xmr-stak-nvidia#36]
Hi Guys,

Aplogies if this is a total noob question but the only 2 instructions provided for Windows are to update the config file (which I did) and then click on the .exe file to run.

However, I have looked through the entire project and can't find a .exe file. I'm wondering if I need to do some sort of build as that's mentioned for linux but I don't know if that's relevant for windows.

Thanks for any help you can provide.

**Comment by psychocrypt** [comment]
You can find the latest release including the compiled `exe` on the main page of github  under [release (klickhere)](https://github.com/fireice-uk/xmr-stak-nvidia/releases).
