### ISSUE TITLE
Threads not calculated correctly with multiple graphics cards

### ISSUE THREAD

**Issue by duel007** [fireice-uk/xmr-stak-nvidia#41]
Hello,

I have noticed today when installing an extra graphics card (550ti) alongside my GTX 950, the autoconfigure reports 

**************** Copy&Paste ****************

"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 32, "blocks" : 18,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  { "index" : 1,
    "threads" : 64, "blocks" : 8,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],

Where index 1 is the GTX550ti, which does not have the capability to run 64 threads. Using that config results in a CUDA lack of memory error, and no mining at all.

When the 950 is disabled, the autoconfigure reports correctly for the 550ti:
"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 32, "blocks" : 8,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],

And can mine on just the 550ti. 

Merging the two configs does allow mining but this isn't the desired result of the autoconfig.

**Comment by psychocrypt** [comment]
Tanks for reporting, I will check the suggestion algorithm and will inform you on this issue as soon as a fix is available.

**Comment by psychocrypt** [comment]
I can reproduce the bug.

**Comment by psychocrypt** [comment]
The ordering is **not** equal to the order from `nvidia-smi`, it looks like the suggestion is correct.

@duel007 How do you know that the GTX550ti is the index 1?
Which operating system (linux or windowd) do you used?

**Comment by duel007** [comment]
@psychocrypt Strange. Perhaps it's just related to this particular workstation.

- I disabled the GTX950 at the OS level and verified that the 950 was not under load and the 550ti was.

- I am running Windows 7, as up to date as it can be. Same for drivers.

Merged is below. I am unsure if it is optimal, but it works as expected.

"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 32, "blocks" : 18,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : true,
  },
  { "index" : 1,
    "threads" : 32, "blocks" : 8,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : true,
  },
],

**Comment by psychocrypt** [comment]
It looks like thatyor 950 can not handle thw suggested 64 threads. Could you please try again the auggested config but with 48 inatead of 64 threads for device 1.

**Comment by duel007** [comment]
The 550ti is device 1, as far as I can tell, and 48/64 are too much for it. The 950 produces slightly less hash at 48 than 32 as well.

**Comment by psychocrypt** [comment]
You should trust the auto suggestion. The order of the devices is in CUDA is not equal to the order of nvidia-smi or any other tool those not using the plain CUDA commands to order the devices.

I spoke with NVIDIA devs and they confirm that the order differ to all tools those using NVML (API to get device information heat, name, ...)
