### ISSUE TITLE
AutoConfig Improvements

### ISSUE THREAD

**Issue by esfomeado** [fireice-uk/xmr-stak-nvidia#43]
Instead of just displaying to the user the recommend settings the miner should auto apply it without the requirement to change the file and restart the miner.
There could be a option "recommend_settings" that will always ignore the values on the config file and in the case that this option is set to false it will just use the values on the file.

**Comment by psychocrypt** [comment]
We discussed this in [#19](https://github.com/fireice-uk/xmr-stak-nvidia/pull/19#issuecomment-293232717) where I introduced this feature, currently the writer is not able to generate humen readable janson files.

I think this feature will come in the future.
