### ISSUE TITLE
Trying to build and run this in ubuntu (16.04 LTS)

### ISSUE THREAD

**Issue by Sviluppo718** [fireice-uk/xmr-stak-nvidia#46]
I *think* I got the build part happening but I'm not sure how to get the application running : P .

Also, in my flailing attempts, I might have altered the default gpu setting (to the k80 GPU because I did get the "nvcc fatal : Unsupported gpu architecture 'compute_60'" error and uncritically followed that response before I thought better of it (my card is a GeForce GTX 1080 from what I've been able to determine).

After I use the ccmake program it configures and generates with no evident output.  Now what though? How do I actually get this application to run (and specifically with the card that would make it functional/optimal).

I would appreciate anyone's expertise on this; out of gratitude I'd strongly consider throwing some XMR or other CryptoNote currency your way if I can get this functioning and mining. ^_^  Thanks

**Comment by psychocrypt** [comment]
Please update your cuda to version 8.0. Currently you are using a old cuda version which is not supporting your gpu.
Than follow [this](https://github.com/fireice-uk/xmr-stak-nvidia#gnu-compiler) steps.
After the miner is compiled run the following steps
```
cd bin
# add your address and pool to the file config.txt
./xmr-stak-nvidia
# copy the shown config suggestion to config.txt
./xmr-stak-nvidia
# you are now mining xmr
```

**Comment by psychocrypt** [comment]
@Sviluppo718 Is your issue solved?

**Comment by Sviluppo718** [comment]
Yes, pretty much (see below though).  Sorry I meant to provide an update in case someone searched for this or a similar issue and stumbled across my post.  

I first updated my Nvidia drivers from the stock that came with this computer.  I had some issues with that though because the Nvidia drivers require X windows to be shut down to install.  This required switching to a virtual terminal.  These five steps **_should be written down_** before anyone attempts this in a Linux distro I think (for reasons indicated in the paragraph below that):

1. Use Ctrl-Alt-F2 to switch to a virtual terminal
2. At the terminal prompt, use the command: "sudo systemctl disable lightdm.service" (disables Xwindows GUI environment).
3. Install the (previously downloaded) updated Nvidia drivers
4. At the terminal, use the command "sudo systemctrl start lightdm.service" (restart your Xwindows GUI unless you want to relive 1980s-era computing ^_^ ).
5.  If applicable (I don't recall if this was actually necessary), use Ctrl-Alt-F7 to switch back.

The slight problem that I haven't resolved is that the hack that allowed the updating of Nvidia drivers has now screwed up my boot sequence.  I now have to do steps 1 and 2 to get my computer nice and functional (non-80s computing) again.  I'll probably figure out through the ubuntu forums how to fix that; **or** I might keep that as a fun feature to make my computer maddeningly private if someone tried to use it without knowing how to make it function (e.g., when I turn the computer on currently all that is visible is a small dot in the center of the screen).  From the dot in the center of the screen, I then have to push Ctrl-Alt-F2 to get a login prompt, I login, and then type the commands listed in step 2 above to get to the graphical interface login prompt that I used to see when I turned the computer on.  

Anyhow, after updating the Nvidia drivers, I did download and install CUDA version 8.  After, that and the building instructions your miner (as I'm pretty sure you're one of the developers) works great.  Congratulations on your awesome coding ^_^. 

I did say I'd try to reward any response through an XMR donation.  As I'm pretty sure you were a developer of this, as the miner is used you do receive a portion of mined XMR, so I will be keeping my word as I use it more.  Thanks for the courtesy of your follow-up too.

**Comment by gwillem** [comment]
Hi and thanks for writing this! I'm stuck on 16.04/GTX1070, with the same error (Unable to query number of CUDA devices). I did:

```
wget cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb
sudo apt -y update
sudo apt -y install cuda
```
Now I have installed:
```
ii  cuda-drivers                                375.26-1                                      amd64        CUDA Driver meta-package
ii  libcuda1-375                                375.66-0ubuntu0.16.04.1                       amd64        NVIDIA CUDA runtime library
ii  nvidia-375                                  375.66-0ubuntu0.16.04.1                       amd64        NVIDIA binary driver - version 375.66
ii  nvidia-375-dev                              375.66-0ubuntu0.16.04.1                       amd64        NVIDIA binary Xorg driver development files
ii  nvidia-modprobe                             375.26-0ubuntu1                               amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-opencl-icd-375                       375.39-0ubuntu0.16.04.1                       amd64        NVIDIA OpenCL ICD
ii  nvidia-settings                             375.26-0ubuntu1                               amd64        Tool for configuring the NVIDIA graphics driver
```
Perhaps cuda-drivers 375.26 conflicts with the existing 375.66 driver (auto installed by Ubuntu)? Will post any updates if I find out more.

**Comment by psychocrypt** [comment]
CUDA 7.5 should be fine as long as you need no Nvidia Pascal support like in your case.
