### ISSUE TITLE
Clang 3.8 not supported?

### ISSUE THREAD

**Issue by Devr0n** [fireice-uk/xmr-stak-nvidia#47]
Hi,
I tryed to compile xmr-stak-nvidia on ubuntu 16.04 with a K80 GPU but i got following error:

make install
[  4%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_core.cu.o
nvcc fatal   : The version ('30800') of the host compiler ('clang') is not supported

How can i handle this problem?

Thanks!

**Comment by psychocrypt** [comment]
This error is coming from from nvcc. 
Depending on your CUDA version nvcc is not compatible with all compiler. 
Which CUDA version you are using? Maybe 7.5?

The easiest way is to use CUDA8 and gcc. 
Or CUDA8 and clang 4.0 (maybe 3.9 is also working) and compile the host and device code with clang [how to](https://github.com/fireice-uk/xmr-stak-nvidia#xmr-stak-nvidia-compile-options).

**Comment by Devr0n** [comment]
Yes i am using 7.5. Ok ill try! Thank you.

**Comment by Devr0n** [comment]
Sorry. No luck. I have istalled CUDA 8 and Clang 4. Then i did:
 cmake . -DCUDA_ARCH=37 -DCUDA_COMPILER=clang
make install 

And get this error:
[  4%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_extra.cu.o
clang: error: cannot find libdevice for sm_37. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.

**Comment by psychocrypt** [comment]
Have you build anything in a clean directory.
Please post the output of the following commands:

```
git status
cmake . -DCUDA_ARCH=37 -DCUDA_COMPILER=clang
make VERBOSE=1
```

**Comment by Devr0n** [comment]
Hi,
here is the output:

root@ubuntu:/opt/xmrminer# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

root@ubuntu:/opt/xmrminer# cmake . -DCUDA_ARCH=37 -DCUDA_COMPILER=clang
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/clang-4.0
-- Check for working C compiler: /usr/bin/clang-4.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr (found suitable version "7.5", minimum required is "7.5")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/xmrminer


root@ubuntu:/opt/xmrminer# make VERBOSE=1
/usr/bin/cmake -H/opt/xmrminer -B/opt/xmrminer --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /opt/xmrminer/CMakeFiles /opt/xmrminer/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/opt/xmrminer'
make -f CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make CMakeFiles/xmr-stak-nvidiaCuda.dir/depend
make[2]: Entering directory '/opt/xmrminer'
cd /opt/xmrminer && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /opt/xmrminer /opt/xmrminer /opt/xmrminer /opt/xmrminer /opt/xmrminer/CMakeFiles/xmr-stak-nvidiaCuda.dir/DependInfo.cmake --color=
Dependee "/opt/xmrminer/CMakeFiles/xmr-stak-nvidiaCuda.dir/DependInfo.cmake" is newer than depender "/opt/xmrminer/CMakeFiles/xmr-stak-nvidiaCuda.dir/depend.internal".
Dependee "/opt/xmrminer/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/opt/xmrminer/CMakeFiles/xmr-stak-nvidiaCuda.dir/depend.internal".
Scanning dependencies of target xmr-stak-nvidiaCuda
make[2]: Leaving directory '/opt/xmrminer'
make -f CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make CMakeFiles/xmr-stak-nvidiaCuda.dir/build
make[2]: Entering directory '/opt/xmrminer'
[  4%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o
/usr/bin/c++   -DXMR_STAK_LARGEGRID=ON -I/opt/xmrminer/.  -msse2 -maes -O3 -DNDEBUG   -O3 -x cuda --cuda-path=/usr -ffp-contract=fast --cuda-gpu-arch=sm_37 -std=c++11 -o CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o -c /opt/xmrminer/nvcc_code/cuda_core.cu
c++: error: unrecognized command line option ‘--cuda-path=/usr’
c++: error: unrecognized command line option ‘--cuda-gpu-arch=sm_37’
CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o] Error 1
make[2]: Leaving directory '/opt/xmrminer'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
make[1]: Leaving directory '/opt/xmrminer'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


Thanks!

**Comment by psychocrypt** [comment]
please run `c++ --version` to be sure that this is the clang compiler

**Comment by Devr0n** [comment]
root@ubuntu:/opt/xmrminer#  c++ --version
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by psychocrypt** [comment]
Ok I found it
```
The CXX compiler identification is GNU 5.4.0
```
You need to use clang as c++ compiler.
`expory CXX=clang-4.0++`

Please xhexk the correct name of the c+q clang compiler I in front of my smartphone and can not check the correct name.

**Comment by Devr0n** [comment]
root@ubuntu:/opt/xmrminer# export CXX=clang-4.0++
root@ubuntu:/opt/xmrminer# make VERBOSE=1
/usr/bin/cmake -H/opt/xmrminer -B/opt/xmrminer --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /opt/xmrminer/CMakeFiles /opt/xmrminer/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/opt/xmrminer'
make -f CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make CMakeFiles/xmr-stak-nvidiaCuda.dir/depend
make[2]: Entering directory '/opt/xmrminer'
cd /opt/xmrminer && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /opt/xmrminer /opt/xmrminer /opt/xmrminer /opt/xmrminer /opt/xmrminer/CMakeFiles/xmr-stak-nvidiaCuda.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/opt/xmrminer'
make -f CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make CMakeFiles/xmr-stak-nvidiaCuda.dir/build
make[2]: Entering directory '/opt/xmrminer'
[  4%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o
/usr/bin/c++   -DXMR_STAK_LARGEGRID=ON -I/opt/xmrminer/.  -msse2 -maes -O3 -DNDEBUG   -O3 -x cuda --cuda-path=/usr -ffp-contract=fast --cuda-gpu-arch=sm_37 -std=c++11 -o CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o -c /opt/xmrminer/nvcc_code/cuda_core.cu
c++: error: unrecognized command line option ‘--cuda-path=/usr’
c++: error: unrecognized command line option ‘--cuda-gpu-arch=sm_37’
CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o] Error 1
make[2]: Leaving directory '/opt/xmrminer'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
make[1]: Leaving directory '/opt/xmrminer'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sviluppo718** [comment]
I'm having very similar issues trying to get the aeon-stak-nvidia miner installed.  There isn't an issues page there so the next-best place I could find was to start entering stuff into the wiki page: 

https://github.com/stoffu/aeon-stak-nvidia/wiki/Compilation-issues-%3F%3F%3F
https://github.com/stoffu/aeon-stak-nvidia/wiki

Good times :P

**Comment by psychocrypt** [comment]
@Sviluppo718 I think the issue from @Devr0n is solved, he used g++ as as C++ compiler and therefore he/she can't compile the device code.
You should format you wiki entry because it is hard to read.
