### ISSUE TITLE
CPU miner lowers GPU hashrate

### ISSUE THREAD

**Issue by andreirusu99** [fireice-uk/xmr-stak-nvidia#48]
Hello! I have an i5 and a gtx 970 in my pc, and when turning on both miners (nvidia and cpu), my gtx hashes at 100H/s and my i5 at 130H/s. This is very low for the 970, as mining with it without the cpu I get 420H/s. Even using affine_to_cpu: 0, I only manage to get 180H/s out of the 970. Please suggest a way to fix this. Thanks a lot!

**Comment by psychocrypt** [comment]
Please remove in the cpu miner config one thread. It looks like all cores are bussy because they are mining and the system can not utilize the gpu.

**Comment by andreirusu99** [comment]
Thanks so much! I had thought that was the problem so I used only 2 threads, but it didn't work. Now using  3 threads, the hash limitation is gone. Thanks again.
