### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Fitzerrick** [fireice-uk/xmr-stak-nvidia#52]
Hello, trying to compile on Manjaro 17.0.1

Here's what I got when I tried the first way shown in the readme:
[michael@REXXYTHESEXXY2 xmr-stak-nvidia-master]$ cmake .
-- The C compiler identification is GNU 7.1.1
-- The CXX compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "8.0", minimum required is "7.5") 
-- Found OpenSSL: /usr/lib/libssl.so (found version "1.1.0f") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/michael/xmr-stak-nvidia-master
[michael@REXXYTHESEXXY2 xmr-stak-nvidia-master]$ make install
Scanning dependencies of target xmr-stak-nvidiaCrypto
[  4%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_blake256.c.o
[  9%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_groestl.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_jh.c.o
[ 19%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_keccak.c.o
[ 23%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_skein.c.o
[ 28%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/soft_aes.c.o
[ 33%] Linking C static library libxmr-stak-nvidiaCrypto.a
[ 33%] Built target xmr-stak-nvidiaCrypto
[ 38%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /opt/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/opt/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
CMake Error at xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o.Release.cmake:222 (message):
  Error generating
  /home/michael/xmr-stak-nvidia-master/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/./xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o

make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:72: CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Then since that didn't work I figured I'd try deleting everything, re-extracting the .zip file and trying it with clang instead: 
[michael@REXXYTHESEXXY2 xmr-stak-nvidia-master]$ export CC=/usr/bin/clang
[michael@REXXYTHESEXXY2 xmr-stak-nvidia-master]$ export CXX=/usr/bin/clang++
[michael@REXXYTHESEXXY2 xmr-stak-nvidia-master]$ cmake .
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "8.0", minimum required is "7.5") 
-- Found OpenSSL: /usr/lib/libssl.so (found version "1.1.0f") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/michael/xmr-stak-nvidia-master
[michael@REXXYTHESEXXY2 xmr-stak-nvidia-master]$ make install
Scanning dependencies of target xmr-stak-nvidiaCrypto
[  4%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_blake256.c.o
[  9%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_groestl.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_jh.c.o
[ 19%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_keccak.c.o
[ 23%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_skein.c.o
[ 28%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/soft_aes.c.o
[ 33%] Linking C static library libxmr-stak-nvidiaCrypto.a
[ 33%] Built target xmr-stak-nvidiaCrypto
[ 38%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('40000') of the host compiler ('clang') is not supported
CMake Error at xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o.Release.cmake:222 (message):
  Error generating
  /home/michael/xmr-stak-nvidia-master/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/./xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o

make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:72: CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Sorry I'm totally new at this, any help would be appreciated.

**Comment by psychocrypt** [comment]
You can't use clang 4.0 with CUDA 8, this is not supported by NVIDIA.
If you follow our README.md and compile everything with clang than it should work

```
cmake . -DCUDA_COMPILER=clang
```

**Comment by Fitzerrick** [comment]
Thankyou so much for taking the time to respond. You're awesome! So once I added that, the compiler made it to 100% and then failed with the same issue as frankcoderL not finding -lcudart_static but as I explained in his thread I think I solved it with another flag. so all in all the commands that worked for me were:

export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
export LDFLAGS=-L/opt/cuda/lib64
cmake . -DCUDA_COMPILER=clang
make install
