### ISSUE TITLE
/usr/bin/ld: cannot find -lcudart_static

### ISSUE THREAD

**Issue by frankcoderL** [fireice-uk/xmr-stak-nvidia#53]
Hello,
I get a linker error at the end of the compilation on Arch Linux.
Any idea's what i'm doing wrong?
Thanks!
*********************
$ export CC=/usr/bin/clang

$ export CXX=/usr/bin/clang++

$ cmake . -DCUDA_COMPILER=clang -DMICROHTTPD_REQUIRED=OFF
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "8.0", minimum required is "7.5") 
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.0f") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/source/xmr-stak-nvidia
$

$ make
Scanning dependencies of target xmr-stak-nvidiaCrypto
[  4%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_blake256.c.o
[  9%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_groestl.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_jh.c.o
[ 19%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_keccak.c.o
[ 23%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_skein.c.o
[ 28%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/soft_aes.c.o
[ 33%] Linking C static library libxmr-stak-nvidiaCrypto.a
[ 33%] Built target xmr-stak-nvidiaCrypto
Scanning dependencies of target xmr-stak-nvidiaCuda
[ 38%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o
[ 42%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_extra.cu.o
[ 47%] Linking CXX static library libxmr-stak-nvidiaCuda.a
[ 47%] Built target xmr-stak-nvidiaCuda
Scanning dependencies of target xmr-stak-nvidia
[ 52%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/cli-miner.cpp.o
[ 57%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/console.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/executor.cpp.o
[ 66%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/httpd.cpp.o
[ 71%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/jconf.cpp.o
[ 76%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/jpsock.cpp.o
[ 80%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/minethd.cpp.o
[ 85%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/socket.cpp.o
[ 90%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/webdesign.cpp.o
[ 95%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/crypto/cryptonight_common.cpp.o
[100%] Linking CXX executable bin/xmr-stak-nvidia
/usr/bin/ld: cannot find -lcudart_static
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/xmr-stak-nvidia.dir/build.make:340: bin/xmr-stak-nvidia] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/xmr-stak-nvidia.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
$

**Comment by psychocrypt** [comment]
try
```
cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF .
```
to use the dynamic runtume environment of CUDA

**Comment by Fitzerrick** [comment]
Once i added -DCUDA_COMPILER=clang to my cmake command (I posted a different issue that psychocrypt responded to) I got to 100% and then got the same error as frankcoderL

I did some googling and found [this askubuntu page](https://askubuntu.com/questions/510176/usr-bin-ld-cannot-find-lcudart) where the second answer by user Benoit explains how to pass a new search location to the linker. My cuda is installed at /opt/cuda/lib64 so all I had to do was do 
export LDFLAGS=-L/opt/cuda/lib64
before my cmake command and then it worked!!!
maybe it will work for you too since you're on arch and I'm on manjaro which is based on arch? I guess check to see if your libcudart_static.a or libcudart_static.so file is in /opt/cuda/lib64 first or do a search for it so you know what path to use. Hope this is helpful. :)

**Comment by frankcoderL** [comment]
Hi,
After a fresh git clone (otherwise it doesn't work) and adding export LDFLAGS, the problem linker is gone :-)
$ export LDFLAGS=-L/opt/cuda/lib64

cmake . -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF 
Doesn't work, but with export LDFLAGS it works also.

Maybe add "export LDFLAGS=-L/opt/cuda/lib64" explanation in the readme file?

Thanks for the help!

**Comment by psychocrypt** [comment]
@frankcoderL If you install a library to non default system places than you need to append always the LD_LIBRARY_PATH. Never the less I found the reason for this issue. 
I added for clang that cuda_static needs to bo linked but not searched for the path. I need to fix it and do some tests. I will anounce the fix in this issue that you can test it.

**Comment by psychocrypt** [comment]
@frankcoderL Could you please test #54 

```
git remote -v psychocrypt https://github.com/psychocrypt/xmr-stak-nvidia.git
git fetch psychocrypt
git checkout psychocrypt/fix-linkError
mkdir build
cd build
cmake .. -DCUDA_COMPILER=clang
make -j install
```

**Comment by frankcoderL** [comment]
Thank you for adding the code howto checkout the development/fix version.
I was reading the github help, and the more I read and tried, the more I was confused how to do this :)
It works on Arch Linux.
All output at below FYI. 

Thanks!

$ export CC=/usr/bin/clang

$ export CXX=/usr/bin/clang++

$ git clone https://github.com/fireice-uk/xmr-stak-nvidia
Cloning into 'xmr-stak-nvidia'...
remote: Counting objects: 287, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 287 (delta 0), reused 2 (delta 0), pack-reused 282
Receiving objects: 100% (287/287), 328.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (132/132), done.

$ git remote add psychocrypt https://github.com/psychocrypt/xmr-stak-nvidia.git

$ git fetch psychocrypt
remote: Counting objects: 66, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 66 (delta 25), reused 29 (delta 25), pack-reused 37
Unpacking objects: 100% (66/66), done.
From https://github.com/psychocrypt/xmr-stak-nvidia
 * [new branch]      fix-linkError                -> psychocrypt/fix-linkError
 * [new branch]      master                       -> psychocrypt/master
 * [new branch]      topic-addPsychocrypt         -> psychocrypt/topic-addPsychocrypt
 * [new branch]      topic-allowDependencyDisable -> psychocrypt/topic-allowDependencyDisable
 * [new branch]      topic-extentDocumentation    -> psychocrypt/topic-extentDocumentation
 * [new branch]      topic-extentGitIgnore        -> psychocrypt/topic-extentGitIgnore
 * [new branch]      topic-interactivity          -> psychocrypt/topic-interactivity
 * [new branch]      topic-versionFile            -> psychocrypt/topic-versionFile
 * [new branch]      topic-visualStudioProject    -> psychocrypt/topic-visualStudioProject
 * [new branch]      topic-windowsBuildSupport    -> psychocrypt/topic-windowsBuildSupport
 * [new branch]      topic-windowsCompileDocu     -> psychocrypt/topic-windowsCompileDocu

$ git checkout psychocrypt/fix-linkError
Note: checking out 'psychocrypt/fix-linkError'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at af0d05c ... fix linker error

$ mkdir build

$ cd build

$ cmake .. -DCUDA_COMPILER=clang
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "8.0", minimum required is "7.5") 
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.0f") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/frank/source/GPU/test/xmr-stak-nvidia/build

$ make
Scanning dependencies of target xmr-stak-nvidiaCrypto
[  4%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_blake256.c.o
[  9%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_groestl.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_jh.c.o
[ 19%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_keccak.c.o
[ 23%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/c_skein.c.o
[ 28%] Building C object CMakeFiles/xmr-stak-nvidiaCrypto.dir/crypto/soft_aes.c.o
[ 33%] Linking C static library libxmr-stak-nvidiaCrypto.a
[ 33%] Built target xmr-stak-nvidiaCrypto
Scanning dependencies of target xmr-stak-nvidiaCuda
[ 38%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o
[ 42%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_extra.cu.o
[ 47%] Linking CXX static library libxmr-stak-nvidiaCuda.a
[ 47%] Built target xmr-stak-nvidiaCuda
Scanning dependencies of target xmr-stak-nvidia
[ 52%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/cli-miner.cpp.o
[ 57%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/console.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/executor.cpp.o
[ 66%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/httpd.cpp.o
[ 71%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/jconf.cpp.o
[ 76%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/jpsock.cpp.o
[ 80%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/minethd.cpp.o
[ 85%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/socket.cpp.o
[ 90%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/webdesign.cpp.o
[ 95%] Building CXX object CMakeFiles/xmr-stak-nvidia.dir/crypto/cryptonight_common.cpp.o
[100%] Linking CXX executable bin/xmr-stak-nvidia
[100%] Built target xmr-stak-nvidia

-> New config.txt format with "daemon_mode" : false,

-> GPU: GeForce GTX 1050 Ti

$xmr-stak-nvidia 

xmr-stak-nvidia 1.4.0-dev mining software, NVIDIA Version.
NVIDIA mining code was written by KlausT and psychocrypt.
Brought to you by fireice_uk under GPLv3.

Configurable dev donation level is set to 1.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection

[2017-06-18 23:06:04] : Connecting to pool pool.minexmr.com:4444 ...
[2017-06-18 23:06:04] : Connected. Logging in...
[2017-06-18 23:06:04] : Difficulty changed. Now: 5000.
[2017-06-18 23:06:04] : New block detected.
[2017-06-18 23:06:17] : New block detected.
[2017-06-18 23:06:26] : Result accepted by the pool.
HASHRATE REPORT
| ID |  10s |  60s |  15m |
|  0 | 305.4 | (na) | (na) |

Totals:   305.4 (na) (na) H/s
Highest:  305.8 H/s
[2017-06-18 23:06:30] : Result accepted by the pool.
HASHRATE REPORT
| ID |  10s |  60s |  15m |
|  0 | 305.8 | (na) | (na) |

Totals:   305.8 (na) (na) H/s
Highest:  305.8 H/s

**Comment by psychocrypt** [comment]
solved, see last post

**Comment by PolarisXQ** [comment]
None of the above solved my problem, but this does
```sudo ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib/libcudart.so```
