### ISSUE TITLE
Working installation instructions

### ISSUE THREAD

**Issue by remon-georgy** [fireice-uk/xmr-stak-nvidia#56]
I realize the title is generic but I tried at least 5 combinations of software and suggestions of yours but to no avail.

Here's my current stack. Please let me know how to get to a working miner:
- Ubuntu 17.04
- GCC 6
- Clang 3.8 and 4.0
- Cuda 8
- NVCC 8.
- GTX 1060 card.
- nvidida 381 driver.

I'd really appreciate having 5-6 steps that just work, Thanks.

**Comment by psychocrypt** [comment]
https://github.com/fireice-uk/xmr-stak-nvidia#compile-on-linux-debian-based-distros

**Comment by remon-georgy** [comment]
Ok sorry to be a pain but I believe that instructions are inconsistent.

So I assume you're suggesting clang. Here's my attempt starting from a clean repo directory:

- sudo apt-get install nvidia-cuda-dev nvidia-cuda-toolkit libmicrohttpd-dev libssl-dev cmake cmake-curses-gui build-essential
- sudo apt-get install clang
- export CC=/usr/bin/clang
- export CXX=/usr/bin/clang++
- cmake . -DCUDA_COMPILER=clang
- make install

Make install spits this error:

```
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_62. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
```

Thanks for your help.

**Comment by remon-georgy** [comment]
It's also worth mentioning this line from cmake . output:

```
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5") 
```

**Comment by remon-georgy** [comment]
Also:

```
cc --version  | grep version
clang version 4.0.0-1ubuntu1 (tags/RELEASE_400/rc1)

cc --version  | grep version
clang version 4.0.0-1ubuntu1 (tags/RELEASE_400/rc1)

echo $CC $CXX
/usr/bin/clang /usr/bin/clang++
```

Is there anything else I should do to make sure CLANG is in use everywhere?

Regarding missing cuda error, is there anything to install besides nvidia-cuda-dev and nvidia-cuda-toolkit?

Thanks

**Comment by remon-georgy** [comment]
Here's another attempt to use GCC 5 instead:

```
cc --version
=> cc (Ubuntu 5.4.1-8ubuntu1) 5.4.1 20170304

c++ --version
=> c++ (Ubuntu 5.4.1-8ubuntu1) 5.4.1 20170304


git clean -rd
export CXX=/usr/bin/g++-5
export CC=/usr/bin/gcc-5

asd@asd:~/projects/xmr-stak-nvidia$ cmake .
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/asd/projects/xmr-stak-nvidia

make install
[  4%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
```
Make hangs on that warning forever. Any clues would be appreciated.

**Comment by remon-georgy** [comment]
Nevermind, GCC 5 build worked. Thank you.

**Comment by psychocrypt** [comment]
@remon-georgy Only as information: The nvcc warning is showing you that fermi GPUs will not longer supported with CUDA9. By default we build for all currently available architectures. To build everything faster you can set the cmake option e.g. `-DCUDA_ARCH=60` (build only for Pascal GPUs).
