### ISSUE TITLE
Optimise CPU side code?

### ISSUE THREAD

**Issue by YellowOnion** [fireice-uk/xmr-stak-nvidia#59]
Hey,

so I've noticed that this app is using ridiculous amounts of CPU (7% total, ~46% of one core).

Meanwhile Claymores AMD miner is using <1% CPU

**Comment by psychocrypt** [comment]
Because claymores amd miner is not mining on nvidia gpus :-)
Xmr-stak is also using near 1% of the cpu resource, if not it could be that you using a to low difficulty or your config is not ideal.
Could you please post your config and the type of your nvidia gpu.

**Comment by YellowOnion** [comment]
These are the best settings I've found on my GTX 760 300 h/s with no UI interference on win10:

{ "index" : 0, "threads" : 40, "blocks" : 12, "bfactor" : 12, "bsleep" :  100, "affine_to_cpu" : false}

diff is fixed to: 5000

**Comment by psychocrypt** [comment]
Your diff is to low therefore you found to much hashes those needs to be double checked on the CPU and mist be send to the pool. Please increase the diff to 15000 or 20000, this should decrease the load.

**Comment by fireice-uk** [comment]
@YellowOnion stak miners double check the hashes on the CPU, claymore doesn't, it will just submit a wrong result and if you overdo it you will get banned by the pool.

**Comment by psychocrypt** [comment]
The reason for the high cpu load can also be the option `"bfactor": 12`. You should decrease bfactor elase many kernel will be started and the load is than generated from the NVidia driver. A normal range for bfactor is 6 - 8

**Comment by YellowOnion** [comment]
Ahh, yes bfactor helps, but sadly my desktop is too unresponsive @8, 12 is needed for Video playback to work.
