### ISSUE TITLE
Settings for GTX 1060?

### ISSUE THREAD

**Issue by stna1981** [fireice-uk/xmr-stak-nvidia#64]
Hi there,

is there a proposal for blocks/threads settings for a GTX1060. The formula described for Maxwell seems to be irrelevant as Pascal GPUs can use up to 16GB of memory, but what values should I use for GTX 1060 to get max hashrate?

Best regards

Stefan

**Comment by psychocrypt** [comment]
A good starting point is the config which is suggested by the miner. Than increase the threads by 8 up to the point the miner crash or the hashrate decrease. In that case begin the decrease the threads by 2. You should find very fast the best values.

**Comment by stna1981** [comment]
With "suggested by the miner" you mean 17/60 like mentioned in the config file? Or does the miner itself make a suggestion, if yes, how do I get that suggestion (mining with Windows x64)?

**Comment by psychocrypt** [comment]
If you start with the config file from the release than you will get the suggestion after the miner starts. You need to copy and past this suggestion to the config.txt. Please use the latest release.

**Comment by stna1981** [comment]
Ok best seems to be 80 threads for me. Anything for the blocks or should they be left untouched?

**Comment by psychocrypt** [comment]
You could try to change the blocks, the default is 3 times number of smx (multiprozessors).
What is the current config and hash rate?

**Comment by stna1981** [comment]
Currently I have 80 threads and 30 blocks, resulting in 465 H/s on a GTX 1060 @ stock

**Comment by psychocrypt** [comment]
please checkout the results on http://monerobenchmarks.info/searchGPU.php sometimes the configuration is included.

**Comment by stna1981** [comment]
Block maximum seems to be already 30 when using 80 threads. Other settings also don't yield better results, so I'll keep these settings.

**Comment by psychocrypt** [comment]
solved
