### ISSUE TITLE
Error GPU 0 Cuda_extra.cu 229

### ISSUE THREAD

**Issue by Hongi** [fireice-uk/xmr-stak-nvidia#66]
When running the dev branch for windows i have this error :
`[CUDA] Error gpu 0: <C:/xmr-stak-dep/xmr-stak-nvidia-dev/nvcc_code/cuda_extra.cu>:229`

GPU : Nvidia Quadro K2200

Config:
`"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 32, "blocks" : 15,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],
` 

build : 
cmake -G "Visual Studio 15 2017 Win64" -DOpenSSL_ENABLE=OFF -DHWLOC_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF -DMICROHTTPD_REQUIRED=OFF -T v140,host=x64 ..

**Comment by Hongi** [comment]
Tried on an other computer
W10 too
GPU : Nvidia GTX750

same bug

**Comment by psychocrypt** [comment]
please reduce the number of blocks and/or number of threads. It looks like you running ouy of memory. Please also post the full error message IMO there are a line above or after the postet error which is important.

**Comment by psychocrypt** [comment]
Do you use the latest dev?

**Comment by Hongi** [comment]
Oh yes, it works ! 
My bad, i used the default setting without playing with threads/blocks factors

**Comment by Hongi** [comment]
The best configuration i found for the quadro is (without GUI lag) :

`
"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 16, "blocks" : 15,
    "bfactor" : 10, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
],
`

**Comment by psychocrypt** [comment]
initial issue is solved

**Comment by imakiro** [comment]
I have the same issue with a 960m :
[CUDA] Error gpu 0: <.....xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:244
I tried different settings of threading, blocks and bfactor yet the software crashes. bfactor between 2 and 8, blocks between 10 and 20 and threads 35 and 10
build command is the same as the build instructions. VS2017 Windows 10 Enterprise 1703.
