### ISSUE TITLE
constant compute errorsq

### ISSUE THREAD

**Issue by flyindata** [fireice-uk/xmr-stak-nvidia#70]
2x GTX1070fe

Error details:
| Count | Error text                       | Last seen           |
|   233 | [GPU COMPUTE ERROR]              | 2017-07-01 18:37:07 |

"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 64, "blocks" : 45,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
  { "index" : 1,
    "threads" : 64, "blocks" : 45,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
],

is this config issue what changes would fix this?

**Comment by psychocrypt** [comment]
Is this the suggested config from the miner?
If not please test to run first the suggested config and than start to tweak the config.

**Comment by flyindata** [comment]
I've gone through hundreds of combinations always errors I think this is a error in the linux complied binary... I'm going to recompile using fedora os instead of ubuntu 16.04
