### ISSUE TITLE
The problem when I compiled on Fedora 25

### ISSUE THREAD

**Issue by nhnc** [fireice-uk/xmr-stak-nvidia#71]
I have installed the kernel-devel dkms-nvidia  nvidia-driver-cuda cuda-devel cuda-cudnn-devel.
But I have CUDA 8.0, and GCC 6, so I tried to use clang to compile it.

# export CC=/usr/bin/clang-3.9
# export CXX=/usr/bin/clang-3.9
# cmake .
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- Check for working C compiler: /usr/bin/clang-3.9
-- Check for working C compiler: /usr/bin/clang-3.9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang-3.9
-- Check for working CXX compiler: /usr/bin/clang-3.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5")
-- Found OpenSSL: /usr/lib64/libssl.so (found version "1.0.2k")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmr-stak-nvidia

# make install
[  4%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('30901') of the host compiler ('clang') is not supported
CMake Error at xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o.Release.cmake:222 (message):
  Error generating
  /root/xmr-stak-nvidia/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/./xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o

CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:70: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

How can I fix that? thanks!

**Comment by psychocrypt** [comment]
cmake . -DCUDA_COMPILER=clang

please the README.md

**Comment by nhnc** [comment]
I have tried that, but that will be another problem when I make install

Scanning dependencies of target xmr-stak-nvidiaCuda
[  4%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-3.9: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by psychocrypt** [comment]
Could you please post the output of a clean cmake within a new folder.
I can only test clang4.0
You could also use the gnu compiler gcc and g++ than everything would be easier because NVIDIA has a better support for this compiler.

**Comment by nhnc** [comment]
It's like no clang4.0 on Fedora 25, only support for Fedora 26.
What version of cuda and gcc should I used? I have tried cuda 8.0 and gcc 4.9, but cmake need gcc 5.1.

the output of a clean cmake:
# export CC=/usr/bin/clang-3.9
# export CXX=/usr/bin/clang-3.9
# cmake . -DCUDA_COMPILER=clang
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- Check for working C compiler: /usr/bin/clang-3.9
-- Check for working C compiler: /usr/bin/clang-3.9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang-3.9
-- Check for working CXX compiler: /usr/bin/clang-3.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5")
-- Found OpenSSL: /usr/lib64/libssl.so (found version "1.0.2k")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmr-stak-nvidia

**Comment by psychocrypt** [comment]
gcc 5.X is needed and cuda 8 is perfect. You could also compile clang from scratch it is not hard but take some time.

**Comment by nhnc** [comment]
Thank u very much!
I installed the compat-gcc-5 and compat-gcc-5-c++ by add the repo from https://copr.fedorainfracloud.org/coprs/leebc/compat-gcc-5/repo/fedora-25/leebc-compat-gcc-5-fedora-25.repo
and set CC=/usr/bin/gcc5 and CXX=/usr/bin/g++5
then it is successful.

**Comment by psychocrypt** [comment]
thx to provide the solution
