### ISSUE TITLE
Unresolved externals

### ISSUE THREAD

**Issue by Gucci360** [fireice-uk/xmr-stak-nvidia#73]
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_core_cpu_hash
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_set_data
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_final
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_init
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_prepare

How to resolve this ?

**Comment by psychocrypt** [comment]
- which branch do you compile? dev or master
- which OS do you use
- please send use the output of cmake and make (from a clean folder)

**Comment by Gucci360** [comment]
I use VS 2015 with cuda_6.5.19_windows_general_64 on Windows 7 64
Not sure what branch i use, i just copy every file and added them on VS project.
I get the follwing err:
1>cli-miner.obj : error LNK2001: unresolved external symbol cuda_get_deviceinfo
1>cli-miner.obj : error LNK2001: unresolved external symbol cuda_get_devicecount
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_core_cpu_hash
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_set_data
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_final
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_init
1>minethd.obj : error LNK2001: unresolved external symbol cryptonight_extra_cpu_prepare
1>C:\Users\wiliamwill\Documents\Visual Studio 2015\Projects\xmr-stak-nvidia\x64\Release\xmr-stak-nvidia.exe : fatal error LNK1120: 7 unresolved externals
Many thanks in advance!

**Comment by psychocrypt** [comment]
Please follow [this instruction](https://github.com/fireice-uk/xmr-stak-nvidia/blob/dev/WINCOMPILE.md) and use the dev branch. 
You need VS2017. Do not create your own VS project elae we can not help, it is not reproduceable.

**Comment by psychocrypt** [comment]
Should be solved with VS2017 and the instructions from the dev branch and if the dev branch ist used.
