### ISSUE TITLE
KeepAlive support

### ISSUE THREAD

**Issue by esfomeado** [fireice-uk/xmr-stak-nvidia#74]

**Comment by fireice-uk** [comment]
You need to be more specific than that.

**Comment by esfomeado** [comment]
From the stratum documentation:
"Client must perform keep-alive HTTP Poll request for indicating it's still alive and want to receive HTTP Push messages"

**Comment by psychocrypt** [comment]
stratum was designed  for light bitcoin wallets and the documentation [link](https://bitcointalk.org/index.php?topic=557866.msg6078244#msg6078244) said `Client must perform keep-alive HTTP Poll request for indicating it’s still alive and want to receive HTTP Push messages. It can be done by crontab entry with one hour period, for example`
This means that it is enough to send a keep-alive each hour, thus we found a block each 2min and hopefully send also a few shares within this time this should be enough that the pool knows that the miner is still active.

Is there a point I missed?
