### ISSUE TITLE
How to auto start on Ubuntu server?

### ISSUE THREAD

**Issue by Arkymedes** [fireice-uk/xmr-stak-nvidia#75]
Hello there, followed the tutorial to the letter and got everything running on an Ubuntu 16.04 minimal server.

Now, since I leave this rig somewhere in the room without a monitor or any other input device attached to it (I manage the server via Putty from Windows), how to make the application auto start at boot?

Stupid question but not very obvious for the Linux's novices out there.

Thank you in advance,
Arky

**Comment by psychocrypt** [comment]
http://www.makeuseof.com/tag/start-applications-automatically-linux-boots/
