### ISSUE TITLE
only using 1 gpu 

### ISSUE THREAD

**Issue by spauldingportraits** [fireice-uk/xmr-stak-nvidia#77]
Hello all. 

slight problem. i've got 4 gpus (nvidia gtx750ti's) and recently found out about xmr-stak. 

compiling it went pretty smooth, but can't seem to figure out how to utilize all 4 of my gpus. 

its currently mining, but only with 1 gpu. here is my gpu thread conf setup. 

"gpu_threads_conf" :
[
        {"index" : 3, "threads" : 4, "blocks" : 60, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false},
],

any help would be greatly appreciated, because until i can figure this out i'm gonna have to go back to ccminer

**Comment by spauldingportraits** [comment]
so after a bit more research, and trial and error. i got it all sorted out. 

i changed my gpu threads conf to this. 

"gpu_threads_conf" :
[
{"index" : 0, "threads" : 4, "blocks" : 60, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false},
{"index" : 1, "threads" : 4, "blocks" : 60, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false},
{"index" : 2, "threads" : 4, "blocks" : 60, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false},
{"index" : 3, "threads" : 4, "blocks" : 60, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false},
],

and it works perfectly now. 

now to tweak it for optimal settings.

**Comment by fireice-uk** [comment]
@psychocrypt What will be useful arch info to dump here? This kind of autoconf failure is probably the most detrimental to the overall experience as an average user, unlike spauldingportraits, might not know what a JSON array is =). If you can get some free time at all next week, I would prioritise it.

**Comment by spauldingportraits** [comment]
thanks for the reply @fireice-uk. unfortunately json and array's are not my strong point. but am a quick learner. 

i was under the preconceived notion that it was setup similar to other miner's. and didn't see anything in the readme on how to setup multiple gpu's. maybe something in there indicating how to for novices such as myself would be helpful and wouldn't take up much time for you amazing developers.

**Comment by fireice-uk** [comment]
If you look at the amd config we had a "gpu_thread_num", which a user would edit first, and since the miner required that number to match the size of the config array, user would be guided a bit through trial-and-error. Of course once we made the autoconfig this became redundant.

Can you check back a couple days later once psychocrypt has a chance to look at it?

**Comment by psychocrypt** [comment]
@fireice-uk It looks like @spauldingportraits has not used the auto suggestion. I think he opened the config file and added directly the example from the documentation. @spauldingportraits  correct me if I am wrong.

**Comment by psychocrypt** [comment]
@fireice-uk What we can do is to start in a interactive mode if no config file is given and ask for the pool, pool password, xmr-address and generate the config file and on the next startup the use must pass the config file to the miner.
Or a more user friendly way, we install the miner without the `config.txt` file and generate the file on the first start (interactive). On the next start we have a config file and use it.

**Comment by fireice-uk** [comment]
@psychocrypt I will let @spauldingportraits confirm but the line in doc is 

` { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},`

whereas he posted

`{"index" : 3, "threads" : 4, "blocks" : 60, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false},`

So it is unlikely that the just copied and pasted the example config, but changed bfactor and bsleep suggest some editing.

@spauldingportraits Can you post what your miner prints with `"gpu_threads_conf" : null,`

**Comment by spauldingportraits** [comment]
@fireice-uk @psychocrypt 

so currently my miner is running on all 4 gpu's. after my initial setup where i did use the auto config, and figured out how to get it to use 4 gpus rather then 1. a rather strange glitch happened regarding my driver and had to remove and reinstall which started a whole slew of other issues compiling. 

this is why i ended up using cmake . rather then ccmake . 

regarding the line's i used, i used the default line from the config.txt file that was created and located in the bin folder. and adjusted for my needs. 

this is my current configuration. 

`"gpu_threads_conf" : 
[
	{ "index" : 0, "threads" : 12, "blocks" : 40, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
	{ "index" : 1, "threads" : 12, "blocks" : 40, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
	{ "index" : 2, "threads" : 12, "blocks" : 40, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
	{ "index" : 3, "threads" : 12, "blocks" : 40, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
],

/`

i will setup a new dev folder and see if i can duplicate the issues i was having regarding the autoconfig.

**Comment by Aspelta** [comment]
Hi All,
I am new here...
went through all (I guess) replies in this topic, and still have an issue.
- Have downloaded compiled version for win10-64bit.
- optimised my config for one GPU (asus strix 980Ti) as 12/44/8/0
- everything works fine at 544H/s

- then I try to add second GPU (same)
![2-gpu config](https://user-images.githubusercontent.com/30846631/29096642-13a84bb6-7c96-11e7-9da0-1b311842d2ea.png)
- and get following error
![2-gpu error](https://user-images.githubusercontent.com/30846631/29096769-b758e3c4-7c96-11e7-8c2b-fecb2d00a4da.png)
What Am I doing wrong?

Thank you for your support.
BR
Aspelta

**Comment by psychocrypt** [comment]
@Aspelta  please begin everything from scratch and skip your manuel configuration. The miner will show you a config after the first start. The suggested config should contain both gpus. Tune the gpu settings based on the suggestion.

**Comment by Aspelta** [comment]
@psychocrypt thank you for quick reply.

> please begin everything from scratch and skip your manuel configuration 

It means that I should compile it, or to start it in "selftuning" mode ?
Here is the problem, How to start it the way that the miner will optimise the config itself?

Thank you in advance,

BR
Aspelta

**Comment by Aspelta** [comment]
work
![works](https://user-images.githubusercontent.com/30846631/29137292-2aaec7a4-7d40-11e7-93d3-99cc00dce262.png)
s now
BR
Aspelta

**Comment by psychocrypt** [comment]
What do you do to solve the issue?

**Comment by Aspelta** [comment]
I guess that I took initially wrong compilation called "xmr-stak-nvidia-win64"
this compilation has differen starting config which has a different first few lines:

> /* 
>  * Number of GPUs that you have in your system. Each GPU will get its own CPU thread.
>  */
> "gpu_thread_num" : 1,
> 
> /*

When I used this config for one GPU everything was going well.

As I wrote, when I have changed then "gpu_thread_num" : 2,
and added second line:

> "gpu_threads_conf" : [ 
> 	{ "index" : 0, "threads" : 8, "blocks" : 66, "bfactor" : 8, "bsleep" :  25, "affine_to_cpu" : false},
> 	{ "index" : 1, "threads" : 8, "blocks" : 66, "bfactor" : 8, "bsleep" :  25, "affine_to_cpu" : false},
> ],
> 

 the whole problem appeared as above.
Hope it is clear
BR
Aspelta

**Comment by fxethos** [comment]
Hi,
i am planning to use a single GTX 1060 3GB to mine. What mining software would u guys suggest?

**Comment by psychocrypt** [comment]
@fxethos You writing to an issue which is open to solve problems. Please ask such questions in a community portal like getmonero.org forum or reddit.com. The best miner is xmr-stak-nvidia ^^

**Comment by psychocrypt** [comment]
issue is solved
