### ISSUE TITLE
Config problem :(

### ISSUE THREAD

**Issue by poluch1** [fireice-uk/xmr-stak-nvidia#80]
Hi Guys Im new hire Im rying to config miner but Im doing something wrong and it doestn wont to start, can somebody post right setup for GTX 1060 6gb, but full file how it looks like . I have error JSON config parse error<ofset 1236>: Missing a coma or'>' after object member. Propably I mised something small and I can not find it olease help :)

**Comment by psychocrypt** [comment]
please post you config

**Comment by Pentoman** [comment]
He didn´t insert the values right , check the copy paste Values in the config.txt under bin, u missed something. 
Its an simple error about the Details inside the config.txt check it again

**Comment by psychocrypt** [comment]
@poluch1  Can I close this issue? or is there still an issue.
