### ISSUE TITLE
Unable to query number of cuda devices

### ISSUE THREAD

**Issue by TrojanZA** [fireice-uk/xmr-stak-nvidia#85]
The screen shot I managed to get just before the app closed had the last line:
Unable to query number of CUDA devices!

Entry in log:
[2017-07-25 23:05:33] : Setup failed for GPU 0. Exitting.

OS: Windows 10
GPU: nvidia 940MX

**Comment by psychocrypt** [comment]
there is something wrong with your cuda driver. Please install the latest cuda driver from the nvidia side.
