### ISSUE TITLE
windows compile error

### ISSUE THREAD

**Issue by dodoei** [fireice-uk/xmr-stak-nvidia#88]
It seems the code needs pthread.h? do I need to get some kind of pthread implementation for windows? Thanks.

I think the build failed probably because of another issue.

 CMake Error at xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj.Release.cmake:222 (message):
    Error generating
    C:/dowload/xmr-stak-nvidia-1.1.1-1.4.0/build/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/Release/xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj
  Failed to run C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/bin (The system cannot find the file specified.).

Is this because "......2017/Community/VC/bin" is not there? Thanks.

**Comment by dodoei** [comment]
Figured it out. In CMakeFiles, change all CUDA_HOST_COMPILER to 

C:/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64

**Comment by NBStephens** [comment]
Brilliant!
