### ISSUE TITLE
Windows 10 claims release exe has trojan

### ISSUE THREAD

**Issue by halsafar** [fireice-uk/xmr-stak-nvidia#90]
Windows Defender flags the current release as malicious because: Win32/Wpakill

Chrome also flags it.

This is not good.

**Comment by aaronsace** [comment]
@halsafar This happens with most miners; it's not a trojan. 

You can report it as a false positive to these companies but nothing will likely change.

**Comment by psychocrypt** [comment]
closed: It is a false positive and can't solved by us. You could compile the miner if you not thrust the binary file.
