### ISSUE TITLE
there is no exe file?

### ISSUE THREAD

**Issue by theBigMan13** [fireice-uk/xmr-stak-nvidia#96]
I just downloaded this twice and there is no .exe file to execute?

What am I meant to do.

Thanks,
Matt.

**Comment by psychocrypt** [comment]
Please post the link from where you are downloading the zip file.

**Comment by theBigMan13** [comment]
https://github.com/fireice-uk/xmr-stak-nvidia here, then pressing clone or download and then downloading the zip.

**Comment by aaronsace** [comment]
@theBigMan13 I think you are new to GitHub. You are on the wrong page: 
https://github.com/fireice-uk/xmr-stak-nvidia/releases

**Comment by theBigMan13** [comment]
Was on the wrong page, thanks.
